syntax = "proto3";
package vx.proxy.shadowsocks;

import "vx/user/user.proto";

option go_package = "buf.build/gen/go/vvvvv/vx/protocolbuffers/go/vx/proxy";

enum ShadowsocksCipherType {
  AES_128_GCM = 0;
  AES_256_GCM = 1;
  CHACHA20_POLY1305 = 2;
  NONE = 3;
}

message ShadowsocksServerConfig {
  reserved 2;
  ShadowsocksCipherType cipher_type = 3;
  bool iv_check = 4;
  vx.user.UserConfig user = 5;
  bool experiment_reduced_iv_head_entropy = 90001;
}

message ShadowsocksClientConfig {
  ShadowsocksCipherType cipher_type = 1;
  string password = 2;
}
