// Code generated by MockGen. DO NOT EDIT.
// Source: .\features\features.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockContainer is a mock of Container interface.
type MockContainer struct {
	ctrl     *gomock.Controller
	recorder *MockContainerMockRecorder
}

// MockContainerMockRecorder is the mock recorder for MockContainer.
type MockContainerMockRecorder struct {
	mock *MockContainer
}

// NewMockContainer creates a new mock instance.
func NewMockContainer(ctrl *gomock.Controller) *MockContainer {
	mock := &MockContainer{ctrl: ctrl}
	mock.recorder = &MockContainerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContainer) EXPECT() *MockContainerMockRecorder {
	return m.recorder
}

// RequireFeatures mocks base method.
func (m *MockContainer) RequireFeatures(callback interface{}, optional bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequireFeatures", callback, optional)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequireFeatures indicates an expected call of RequireFeatures.
func (mr *MockContainerMockRecorder) RequireFeatures(callback, optional interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequireFeatures", reflect.TypeOf((*MockContainer)(nil).RequireFeatures), callback, optional)
}
