// Code generated by MockGen. DO NOT EDIT.
// Source: ../../i/i.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	netip "net/netip"
	reflect "reflect"
	atomic "sync/atomic"
	time "time"

	buf "github.com/5vnetwork/vx-core/common/buf"
	net "github.com/5vnetwork/vx-core/common/net"
	udp "github.com/5vnetwork/vx-core/common/net/udp"
	pipe "github.com/5vnetwork/vx-core/common/pipe"
	session "github.com/5vnetwork/vx-core/common/session"
	uuid "github.com/5vnetwork/vx-core/common/uuid"
	i "github.com/5vnetwork/vx-core/i"
	gomock "github.com/golang/mock/gomock"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// HandleFlow mocks base method.
func (m *MockHandler) HandleFlow(ctx context.Context, info *session.Info, rw buf.ReaderWriter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleFlow", ctx, info, rw)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleFlow indicates an expected call of HandleFlow.
func (mr *MockHandlerMockRecorder) HandleFlow(ctx, info, rw interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleFlow", reflect.TypeOf((*MockHandler)(nil).HandleFlow), ctx, info, rw)
}

// HandlePacketConn mocks base method.
func (m *MockHandler) HandlePacketConn(ctx context.Context, info *session.Info, p udp.PacketReaderWriter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandlePacketConn", ctx, info, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandlePacketConn indicates an expected call of HandlePacketConn.
func (mr *MockHandlerMockRecorder) HandlePacketConn(ctx, info, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandlePacketConn", reflect.TypeOf((*MockHandler)(nil).HandlePacketConn), ctx, info, p)
}

// MockFlowHandler is a mock of FlowHandler interface.
type MockFlowHandler struct {
	ctrl     *gomock.Controller
	recorder *MockFlowHandlerMockRecorder
}

// MockFlowHandlerMockRecorder is the mock recorder for MockFlowHandler.
type MockFlowHandlerMockRecorder struct {
	mock *MockFlowHandler
}

// NewMockFlowHandler creates a new mock instance.
func NewMockFlowHandler(ctrl *gomock.Controller) *MockFlowHandler {
	mock := &MockFlowHandler{ctrl: ctrl}
	mock.recorder = &MockFlowHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlowHandler) EXPECT() *MockFlowHandlerMockRecorder {
	return m.recorder
}

// HandleFlow mocks base method.
func (m *MockFlowHandler) HandleFlow(ctx context.Context, info *session.Info, rw buf.ReaderWriter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleFlow", ctx, info, rw)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleFlow indicates an expected call of HandleFlow.
func (mr *MockFlowHandlerMockRecorder) HandleFlow(ctx, info, rw interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleFlow", reflect.TypeOf((*MockFlowHandler)(nil).HandleFlow), ctx, info, rw)
}

// MockProxyClient is a mock of ProxyClient interface.
type MockProxyClient struct {
	ctrl     *gomock.Controller
	recorder *MockProxyClientMockRecorder
}

// MockProxyClientMockRecorder is the mock recorder for MockProxyClient.
type MockProxyClientMockRecorder struct {
	mock *MockProxyClient
}

// NewMockProxyClient creates a new mock instance.
func NewMockProxyClient(ctrl *gomock.Controller) *MockProxyClient {
	mock := &MockProxyClient{ctrl: ctrl}
	mock.recorder = &MockProxyClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProxyClient) EXPECT() *MockProxyClientMockRecorder {
	return m.recorder
}

// HandleFlow mocks base method.
func (m *MockProxyClient) HandleFlow(ctx context.Context, info *session.Info, rw buf.ReaderWriter, dialer i.Dialer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleFlow", ctx, info, rw, dialer)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleFlow indicates an expected call of HandleFlow.
func (mr *MockProxyClientMockRecorder) HandleFlow(ctx, info, rw, dialer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleFlow", reflect.TypeOf((*MockProxyClient)(nil).HandleFlow), ctx, info, rw, dialer)
}

// HandlePacketConn mocks base method.
func (m *MockProxyClient) HandlePacketConn(ctx context.Context, info *session.Info, pc udp.PacketReaderWriter, dialer i.Dialer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandlePacketConn", ctx, info, pc, dialer)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandlePacketConn indicates an expected call of HandlePacketConn.
func (mr *MockProxyClientMockRecorder) HandlePacketConn(ctx, info, pc, dialer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandlePacketConn", reflect.TypeOf((*MockProxyClient)(nil).HandlePacketConn), ctx, info, pc, dialer)
}

// MockPacketHandler is a mock of PacketHandler interface.
type MockPacketHandler struct {
	ctrl     *gomock.Controller
	recorder *MockPacketHandlerMockRecorder
}

// MockPacketHandlerMockRecorder is the mock recorder for MockPacketHandler.
type MockPacketHandlerMockRecorder struct {
	mock *MockPacketHandler
}

// NewMockPacketHandler creates a new mock instance.
func NewMockPacketHandler(ctrl *gomock.Controller) *MockPacketHandler {
	mock := &MockPacketHandler{ctrl: ctrl}
	mock.recorder = &MockPacketHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPacketHandler) EXPECT() *MockPacketHandlerMockRecorder {
	return m.recorder
}

// HandlePacketConn mocks base method.
func (m *MockPacketHandler) HandlePacketConn(ctx context.Context, info *session.Info, p udp.PacketReaderWriter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandlePacketConn", ctx, info, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandlePacketConn indicates an expected call of HandlePacketConn.
func (mr *MockPacketHandlerMockRecorder) HandlePacketConn(ctx, info, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandlePacketConn", reflect.TypeOf((*MockPacketHandler)(nil).HandlePacketConn), ctx, info, p)
}

// MockDispatcher is a mock of Dispatcher interface.
type MockDispatcher struct {
	ctrl     *gomock.Controller
	recorder *MockDispatcherMockRecorder
}

// MockDispatcherMockRecorder is the mock recorder for MockDispatcher.
type MockDispatcherMockRecorder struct {
	mock *MockDispatcher
}

// NewMockDispatcher creates a new mock instance.
func NewMockDispatcher(ctrl *gomock.Controller) *MockDispatcher {
	mock := &MockDispatcher{ctrl: ctrl}
	mock.recorder = &MockDispatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDispatcher) EXPECT() *MockDispatcherMockRecorder {
	return m.recorder
}

// Dispatch mocks base method.
func (m *MockDispatcher) Dispatch(arg0 context.Context, arg1 net.Destination) (*pipe.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dispatch", arg0, arg1)
	ret0, _ := ret[0].(*pipe.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dispatch indicates an expected call of Dispatch.
func (mr *MockDispatcherMockRecorder) Dispatch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dispatch", reflect.TypeOf((*MockDispatcher)(nil).Dispatch), arg0, arg1)
}

// MockMyConn is a mock of MyConn interface.
type MockMyConn struct {
	ctrl     *gomock.Controller
	recorder *MockMyConnMockRecorder
}

// MockMyConnMockRecorder is the mock recorder for MockMyConn.
type MockMyConnMockRecorder struct {
	mock *MockMyConn
}

// NewMockMyConn creates a new mock instance.
func NewMockMyConn(ctrl *gomock.Controller) *MockMyConn {
	mock := &MockMyConn{ctrl: ctrl}
	mock.recorder = &MockMyConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMyConn) EXPECT() *MockMyConnMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockMyConn) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockMyConnMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMyConn)(nil).Close))
}

// CloseWrite mocks base method.
func (m *MockMyConn) CloseWrite() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseWrite")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseWrite indicates an expected call of CloseWrite.
func (mr *MockMyConnMockRecorder) CloseWrite() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseWrite", reflect.TypeOf((*MockMyConn)(nil).CloseWrite))
}

// ReadMultiBuffer mocks base method.
func (m *MockMyConn) ReadMultiBuffer() (buf.MultiBuffer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadMultiBuffer")
	ret0, _ := ret[0].(buf.MultiBuffer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadMultiBuffer indicates an expected call of ReadMultiBuffer.
func (mr *MockMyConnMockRecorder) ReadMultiBuffer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadMultiBuffer", reflect.TypeOf((*MockMyConn)(nil).ReadMultiBuffer))
}

// WriteMultiBuffer mocks base method.
func (m *MockMyConn) WriteMultiBuffer(arg0 buf.MultiBuffer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteMultiBuffer", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteMultiBuffer indicates an expected call of WriteMultiBuffer.
func (mr *MockMyConnMockRecorder) WriteMultiBuffer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteMultiBuffer", reflect.TypeOf((*MockMyConn)(nil).WriteMultiBuffer), arg0)
}

// MockMyPacketConn is a mock of MyPacketConn interface.
type MockMyPacketConn struct {
	ctrl     *gomock.Controller
	recorder *MockMyPacketConnMockRecorder
}

// MockMyPacketConnMockRecorder is the mock recorder for MockMyPacketConn.
type MockMyPacketConnMockRecorder struct {
	mock *MockMyPacketConn
}

// NewMockMyPacketConn creates a new mock instance.
func NewMockMyPacketConn(ctrl *gomock.Controller) *MockMyPacketConn {
	mock := &MockMyPacketConn{ctrl: ctrl}
	mock.recorder = &MockMyPacketConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMyPacketConn) EXPECT() *MockMyPacketConnMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockMyPacketConn) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockMyPacketConnMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMyPacketConn)(nil).Close))
}

// ReadPacket mocks base method.
func (m *MockMyPacketConn) ReadPacket() (*udp.Packet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadPacket")
	ret0, _ := ret[0].(*udp.Packet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadPacket indicates an expected call of ReadPacket.
func (mr *MockMyPacketConnMockRecorder) ReadPacket() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadPacket", reflect.TypeOf((*MockMyPacketConn)(nil).ReadPacket))
}

// WritePacket mocks base method.
func (m *MockMyPacketConn) WritePacket(p *udp.Packet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WritePacket", p)
	ret0, _ := ret[0].(error)
	return ret0
}

// WritePacket indicates an expected call of WritePacket.
func (mr *MockMyPacketConnMockRecorder) WritePacket(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WritePacket", reflect.TypeOf((*MockMyPacketConn)(nil).WritePacket), p)
}

// MockNamedHandler is a mock of NamedHandler interface.
type MockNamedHandler struct {
	ctrl     *gomock.Controller
	recorder *MockNamedHandlerMockRecorder
}

// MockNamedHandlerMockRecorder is the mock recorder for MockNamedHandler.
type MockNamedHandlerMockRecorder struct {
	mock *MockNamedHandler
}

// NewMockNamedHandler creates a new mock instance.
func NewMockNamedHandler(ctrl *gomock.Controller) *MockNamedHandler {
	mock := &MockNamedHandler{ctrl: ctrl}
	mock.recorder = &MockNamedHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNamedHandler) EXPECT() *MockNamedHandlerMockRecorder {
	return m.recorder
}

// HandleFlow mocks base method.
func (m *MockNamedHandler) HandleFlow(ctx context.Context, info *session.Info, rw buf.ReaderWriter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleFlow", ctx, info, rw)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleFlow indicates an expected call of HandleFlow.
func (mr *MockNamedHandlerMockRecorder) HandleFlow(ctx, info, rw interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleFlow", reflect.TypeOf((*MockNamedHandler)(nil).HandleFlow), ctx, info, rw)
}

// HandlePacketConn mocks base method.
func (m *MockNamedHandler) HandlePacketConn(ctx context.Context, info *session.Info, p udp.PacketReaderWriter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandlePacketConn", ctx, info, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandlePacketConn indicates an expected call of HandlePacketConn.
func (mr *MockNamedHandlerMockRecorder) HandlePacketConn(ctx, info, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandlePacketConn", reflect.TypeOf((*MockNamedHandler)(nil).HandlePacketConn), ctx, info, p)
}

// Tag mocks base method.
func (m *MockNamedHandler) Tag() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tag")
	ret0, _ := ret[0].(string)
	return ret0
}

// Tag indicates an expected call of Tag.
func (mr *MockNamedHandlerMockRecorder) Tag() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tag", reflect.TypeOf((*MockNamedHandler)(nil).Tag))
}

// MockHandlerWith6Info is a mock of HandlerWith6Info interface.
type MockHandlerWith6Info struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerWith6InfoMockRecorder
}

// MockHandlerWith6InfoMockRecorder is the mock recorder for MockHandlerWith6Info.
type MockHandlerWith6InfoMockRecorder struct {
	mock *MockHandlerWith6Info
}

// NewMockHandlerWith6Info creates a new mock instance.
func NewMockHandlerWith6Info(ctrl *gomock.Controller) *MockHandlerWith6Info {
	mock := &MockHandlerWith6Info{ctrl: ctrl}
	mock.recorder = &MockHandlerWith6InfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandlerWith6Info) EXPECT() *MockHandlerWith6InfoMockRecorder {
	return m.recorder
}

// HandleFlow mocks base method.
func (m *MockHandlerWith6Info) HandleFlow(ctx context.Context, info *session.Info, rw buf.ReaderWriter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleFlow", ctx, info, rw)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleFlow indicates an expected call of HandleFlow.
func (mr *MockHandlerWith6InfoMockRecorder) HandleFlow(ctx, info, rw interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleFlow", reflect.TypeOf((*MockHandlerWith6Info)(nil).HandleFlow), ctx, info, rw)
}

// HandlePacketConn mocks base method.
func (m *MockHandlerWith6Info) HandlePacketConn(ctx context.Context, info *session.Info, p udp.PacketReaderWriter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandlePacketConn", ctx, info, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandlePacketConn indicates an expected call of HandlePacketConn.
func (mr *MockHandlerWith6InfoMockRecorder) HandlePacketConn(ctx, info, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandlePacketConn", reflect.TypeOf((*MockHandlerWith6Info)(nil).HandlePacketConn), ctx, info, p)
}

// Support6 mocks base method.
func (m *MockHandlerWith6Info) Support6() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Support6")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Support6 indicates an expected call of Support6.
func (mr *MockHandlerWith6InfoMockRecorder) Support6() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Support6", reflect.TypeOf((*MockHandlerWith6Info)(nil).Support6))
}

// Tag mocks base method.
func (m *MockHandlerWith6Info) Tag() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tag")
	ret0, _ := ret[0].(string)
	return ret0
}

// Tag indicates an expected call of Tag.
func (mr *MockHandlerWith6InfoMockRecorder) Tag() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tag", reflect.TypeOf((*MockHandlerWith6Info)(nil).Tag))
}

// MockGeoHelper is a mock of GeoHelper interface.
type MockGeoHelper struct {
	ctrl     *gomock.Controller
	recorder *MockGeoHelperMockRecorder
}

// MockGeoHelperMockRecorder is the mock recorder for MockGeoHelper.
type MockGeoHelperMockRecorder struct {
	mock *MockGeoHelper
}

// NewMockGeoHelper creates a new mock instance.
func NewMockGeoHelper(ctrl *gomock.Controller) *MockGeoHelper {
	mock := &MockGeoHelper{ctrl: ctrl}
	mock.recorder = &MockGeoHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGeoHelper) EXPECT() *MockGeoHelperMockRecorder {
	return m.recorder
}

// MatchAppId mocks base method.
func (m *MockGeoHelper) MatchAppId(appId, tag string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MatchAppId", appId, tag)
	ret0, _ := ret[0].(bool)
	return ret0
}

// MatchAppId indicates an expected call of MatchAppId.
func (mr *MockGeoHelperMockRecorder) MatchAppId(appId, tag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MatchAppId", reflect.TypeOf((*MockGeoHelper)(nil).MatchAppId), appId, tag)
}

// MatchDomain mocks base method.
func (m *MockGeoHelper) MatchDomain(domain, tag string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MatchDomain", domain, tag)
	ret0, _ := ret[0].(bool)
	return ret0
}

// MatchDomain indicates an expected call of MatchDomain.
func (mr *MockGeoHelperMockRecorder) MatchDomain(domain, tag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MatchDomain", reflect.TypeOf((*MockGeoHelper)(nil).MatchDomain), domain, tag)
}

// MatchIP mocks base method.
func (m *MockGeoHelper) MatchIP(ip net.IP, tag string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MatchIP", ip, tag)
	ret0, _ := ret[0].(bool)
	return ret0
}

// MatchIP indicates an expected call of MatchIP.
func (mr *MockGeoHelperMockRecorder) MatchIP(ip, tag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MatchIP", reflect.TypeOf((*MockGeoHelper)(nil).MatchIP), ip, tag)
}

// MockTimeoutSetting is a mock of TimeoutSetting interface.
type MockTimeoutSetting struct {
	ctrl     *gomock.Controller
	recorder *MockTimeoutSettingMockRecorder
}

// MockTimeoutSettingMockRecorder is the mock recorder for MockTimeoutSetting.
type MockTimeoutSettingMockRecorder struct {
	mock *MockTimeoutSetting
}

// NewMockTimeoutSetting creates a new mock instance.
func NewMockTimeoutSetting(ctrl *gomock.Controller) *MockTimeoutSetting {
	mock := &MockTimeoutSetting{ctrl: ctrl}
	mock.recorder = &MockTimeoutSettingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimeoutSetting) EXPECT() *MockTimeoutSettingMockRecorder {
	return m.recorder
}

// DnsIdleTimeout mocks base method.
func (m *MockTimeoutSetting) DnsIdleTimeout() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DnsIdleTimeout")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// DnsIdleTimeout indicates an expected call of DnsIdleTimeout.
func (mr *MockTimeoutSettingMockRecorder) DnsIdleTimeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DnsIdleTimeout", reflect.TypeOf((*MockTimeoutSetting)(nil).DnsIdleTimeout))
}

// DownLinkOnlyTimeout mocks base method.
func (m *MockTimeoutSetting) DownLinkOnlyTimeout() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownLinkOnlyTimeout")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// DownLinkOnlyTimeout indicates an expected call of DownLinkOnlyTimeout.
func (mr *MockTimeoutSettingMockRecorder) DownLinkOnlyTimeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownLinkOnlyTimeout", reflect.TypeOf((*MockTimeoutSetting)(nil).DownLinkOnlyTimeout))
}

// HandshakeTimeout mocks base method.
func (m *MockTimeoutSetting) HandshakeTimeout() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandshakeTimeout")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// HandshakeTimeout indicates an expected call of HandshakeTimeout.
func (mr *MockTimeoutSettingMockRecorder) HandshakeTimeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandshakeTimeout", reflect.TypeOf((*MockTimeoutSetting)(nil).HandshakeTimeout))
}

// TcpIdleTimeout mocks base method.
func (m *MockTimeoutSetting) TcpIdleTimeout() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TcpIdleTimeout")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// TcpIdleTimeout indicates an expected call of TcpIdleTimeout.
func (mr *MockTimeoutSettingMockRecorder) TcpIdleTimeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TcpIdleTimeout", reflect.TypeOf((*MockTimeoutSetting)(nil).TcpIdleTimeout))
}

// UdpIdleTimeout mocks base method.
func (m *MockTimeoutSetting) UdpIdleTimeout() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UdpIdleTimeout")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// UdpIdleTimeout indicates an expected call of UdpIdleTimeout.
func (mr *MockTimeoutSettingMockRecorder) UdpIdleTimeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UdpIdleTimeout", reflect.TypeOf((*MockTimeoutSetting)(nil).UdpIdleTimeout))
}

// UpLinkOnlyTimeout mocks base method.
func (m *MockTimeoutSetting) UpLinkOnlyTimeout() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpLinkOnlyTimeout")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// UpLinkOnlyTimeout indicates an expected call of UpLinkOnlyTimeout.
func (mr *MockTimeoutSettingMockRecorder) UpLinkOnlyTimeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpLinkOnlyTimeout", reflect.TypeOf((*MockTimeoutSetting)(nil).UpLinkOnlyTimeout))
}

// MockStatsSetting is a mock of StatsSetting interface.
type MockStatsSetting struct {
	ctrl     *gomock.Controller
	recorder *MockStatsSettingMockRecorder
}

// MockStatsSettingMockRecorder is the mock recorder for MockStatsSetting.
type MockStatsSettingMockRecorder struct {
	mock *MockStatsSetting
}

// NewMockStatsSetting creates a new mock instance.
func NewMockStatsSetting(ctrl *gomock.Controller) *MockStatsSetting {
	mock := &MockStatsSetting{ctrl: ctrl}
	mock.recorder = &MockStatsSettingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsSetting) EXPECT() *MockStatsSettingMockRecorder {
	return m.recorder
}

// CalculateInboundStats mocks base method.
func (m *MockStatsSetting) CalculateInboundStats() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateInboundStats")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CalculateInboundStats indicates an expected call of CalculateInboundStats.
func (mr *MockStatsSettingMockRecorder) CalculateInboundStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateInboundStats", reflect.TypeOf((*MockStatsSetting)(nil).CalculateInboundStats))
}

// CalculateInboundLinkStats mocks base method.
func (m *MockStatsSetting) CalculateInboundLinkStats() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateInboundLinkStats")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CalculateInboundLinkStats indicates an expected call of CalculateInboundLinkStats.
func (mr *MockStatsSettingMockRecorder) CalculateInboundLinkStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateInboundLinkStats", reflect.TypeOf((*MockStatsSetting)(nil).CalculateInboundLinkStats))
}

// CalculateOutboundLinkStats mocks base method.
func (m *MockStatsSetting) CalculateOutboundLinkStats() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateOutboundLinkStats")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CalculateOutboundLinkStats indicates an expected call of CalculateOutboundLinkStats.
func (mr *MockStatsSettingMockRecorder) CalculateOutboundLinkStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateOutboundLinkStats", reflect.TypeOf((*MockStatsSetting)(nil).CalculateOutboundLinkStats))
}

// CalculateSessionStats mocks base method.
func (m *MockStatsSetting) CalculateSessionStats() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateSessionStats")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CalculateSessionStats indicates an expected call of CalculateSessionStats.
func (mr *MockStatsSettingMockRecorder) CalculateSessionStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateSessionStats", reflect.TypeOf((*MockStatsSetting)(nil).CalculateSessionStats))
}

// CalculateUserStats mocks base method.
func (m *MockStatsSetting) CalculateUserStats() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateUserStats")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CalculateUserStats indicates an expected call of CalculateUserStats.
func (mr *MockStatsSettingMockRecorder) CalculateUserStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateUserStats", reflect.TypeOf((*MockStatsSetting)(nil).CalculateUserStats))
}

// MockBufferPolicy is a mock of BufferPolicy interface.
type MockBufferPolicy struct {
	ctrl     *gomock.Controller
	recorder *MockBufferPolicyMockRecorder
}

// MockBufferPolicyMockRecorder is the mock recorder for MockBufferPolicy.
type MockBufferPolicyMockRecorder struct {
	mock *MockBufferPolicy
}

// NewMockBufferPolicy creates a new mock instance.
func NewMockBufferPolicy(ctrl *gomock.Controller) *MockBufferPolicy {
	mock := &MockBufferPolicy{ctrl: ctrl}
	mock.recorder = &MockBufferPolicyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBufferPolicy) EXPECT() *MockBufferPolicyMockRecorder {
	return m.recorder
}

// UserBufferSize mocks base method.
func (m *MockBufferPolicy) UserBufferSize(level uint32) int32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserBufferSize", level)
	ret0, _ := ret[0].(int32)
	return ret0
}

// UserBufferSize indicates an expected call of UserBufferSize.
func (mr *MockBufferPolicyMockRecorder) UserBufferSize(level interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserBufferSize", reflect.TypeOf((*MockBufferPolicy)(nil).UserBufferSize), level)
}

// MockIPSet is a mock of IPSet interface.
type MockIPSet struct {
	ctrl     *gomock.Controller
	recorder *MockIPSetMockRecorder
}

// MockIPSetMockRecorder is the mock recorder for MockIPSet.
type MockIPSetMockRecorder struct {
	mock *MockIPSet
}

// NewMockIPSet creates a new mock instance.
func NewMockIPSet(ctrl *gomock.Controller) *MockIPSet {
	mock := &MockIPSet{ctrl: ctrl}
	mock.recorder = &MockIPSetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPSet) EXPECT() *MockIPSetMockRecorder {
	return m.recorder
}

// Match mocks base method.
func (m *MockIPSet) Match(ip net.IP) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Match", ip)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Match indicates an expected call of Match.
func (mr *MockIPSetMockRecorder) Match(ip interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Match", reflect.TypeOf((*MockIPSet)(nil).Match), ip)
}

// MockDomainSet is a mock of DomainSet interface.
type MockDomainSet struct {
	ctrl     *gomock.Controller
	recorder *MockDomainSetMockRecorder
}

// MockDomainSetMockRecorder is the mock recorder for MockDomainSet.
type MockDomainSetMockRecorder struct {
	mock *MockDomainSet
}

// NewMockDomainSet creates a new mock instance.
func NewMockDomainSet(ctrl *gomock.Controller) *MockDomainSet {
	mock := &MockDomainSet{ctrl: ctrl}
	mock.recorder = &MockDomainSetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDomainSet) EXPECT() *MockDomainSetMockRecorder {
	return m.recorder
}

// Match mocks base method.
func (m *MockDomainSet) Match(domain string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Match", domain)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Match indicates an expected call of Match.
func (mr *MockDomainSetMockRecorder) Match(domain interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Match", reflect.TypeOf((*MockDomainSet)(nil).Match), domain)
}

// MockAppSet is a mock of AppSet interface.
type MockAppSet struct {
	ctrl     *gomock.Controller
	recorder *MockAppSetMockRecorder
}

// MockAppSetMockRecorder is the mock recorder for MockAppSet.
type MockAppSetMockRecorder struct {
	mock *MockAppSet
}

// NewMockAppSet creates a new mock instance.
func NewMockAppSet(ctrl *gomock.Controller) *MockAppSet {
	mock := &MockAppSet{ctrl: ctrl}
	mock.recorder = &MockAppSetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppSet) EXPECT() *MockAppSetMockRecorder {
	return m.recorder
}

// Match mocks base method.
func (m *MockAppSet) Match(appId string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Match", appId)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Match indicates an expected call of Match.
func (mr *MockAppSetMockRecorder) Match(appId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Match", reflect.TypeOf((*MockAppSet)(nil).Match), appId)
}

// MockDialer is a mock of Dialer interface.
type MockDialer struct {
	ctrl     *gomock.Controller
	recorder *MockDialerMockRecorder
}

// MockDialerMockRecorder is the mock recorder for MockDialer.
type MockDialerMockRecorder struct {
	mock *MockDialer
}

// NewMockDialer creates a new mock instance.
func NewMockDialer(ctrl *gomock.Controller) *MockDialer {
	mock := &MockDialer{ctrl: ctrl}
	mock.recorder = &MockDialerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDialer) EXPECT() *MockDialerMockRecorder {
	return m.recorder
}

// Dial mocks base method.
func (m *MockDialer) Dial(ctx context.Context, dst net.Destination) (net.Conn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dial", ctx, dst)
	ret0, _ := ret[0].(net.Conn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dial indicates an expected call of Dial.
func (mr *MockDialerMockRecorder) Dial(ctx, dst interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dial", reflect.TypeOf((*MockDialer)(nil).Dial), ctx, dst)
}

// MockRunnableDialer is a mock of RunnableDialer interface.
type MockRunnableDialer struct {
	ctrl     *gomock.Controller
	recorder *MockRunnableDialerMockRecorder
}

// MockRunnableDialerMockRecorder is the mock recorder for MockRunnableDialer.
type MockRunnableDialerMockRecorder struct {
	mock *MockRunnableDialer
}

// NewMockRunnableDialer creates a new mock instance.
func NewMockRunnableDialer(ctrl *gomock.Controller) *MockRunnableDialer {
	mock := &MockRunnableDialer{ctrl: ctrl}
	mock.recorder = &MockRunnableDialerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunnableDialer) EXPECT() *MockRunnableDialerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRunnableDialer) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRunnableDialerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRunnableDialer)(nil).Close))
}

// Dial mocks base method.
func (m *MockRunnableDialer) Dial(ctx context.Context, dst net.Destination) (net.Conn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dial", ctx, dst)
	ret0, _ := ret[0].(net.Conn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dial indicates an expected call of Dial.
func (mr *MockRunnableDialerMockRecorder) Dial(ctx, dst interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dial", reflect.TypeOf((*MockRunnableDialer)(nil).Dial), ctx, dst)
}

// Start mocks base method.
func (m *MockRunnableDialer) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockRunnableDialerMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockRunnableDialer)(nil).Start))
}

// MockPacketListener is a mock of PacketListener interface.
type MockPacketListener struct {
	ctrl     *gomock.Controller
	recorder *MockPacketListenerMockRecorder
}

// MockPacketListenerMockRecorder is the mock recorder for MockPacketListener.
type MockPacketListenerMockRecorder struct {
	mock *MockPacketListener
}

// NewMockPacketListener creates a new mock instance.
func NewMockPacketListener(ctrl *gomock.Controller) *MockPacketListener {
	mock := &MockPacketListener{ctrl: ctrl}
	mock.recorder = &MockPacketListenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPacketListener) EXPECT() *MockPacketListenerMockRecorder {
	return m.recorder
}

// ListenPacket mocks base method.
func (m *MockPacketListener) ListenPacket(ctx context.Context, network, address string) (net.PacketConn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenPacket", ctx, network, address)
	ret0, _ := ret[0].(net.PacketConn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListenPacket indicates an expected call of ListenPacket.
func (mr *MockPacketListenerMockRecorder) ListenPacket(ctx, network, address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenPacket", reflect.TypeOf((*MockPacketListener)(nil).ListenPacket), ctx, network, address)
}

// MockListener is a mock of Listener interface.
type MockListener struct {
	ctrl     *gomock.Controller
	recorder *MockListenerMockRecorder
}

// MockListenerMockRecorder is the mock recorder for MockListener.
type MockListenerMockRecorder struct {
	mock *MockListener
}

// NewMockListener creates a new mock instance.
func NewMockListener(ctrl *gomock.Controller) *MockListener {
	mock := &MockListener{ctrl: ctrl}
	mock.recorder = &MockListenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListener) EXPECT() *MockListenerMockRecorder {
	return m.recorder
}

// Listen mocks base method.
func (m *MockListener) Listen(ctx context.Context, addr net.Addr) (net.Listener, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Listen", ctx, addr)
	ret0, _ := ret[0].(net.Listener)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Listen indicates an expected call of Listen.
func (mr *MockListenerMockRecorder) Listen(ctx, addr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Listen", reflect.TypeOf((*MockListener)(nil).Listen), ctx, addr)
}

// MockDialerListener is a mock of DialerListener interface.
type MockDialerListener struct {
	ctrl     *gomock.Controller
	recorder *MockDialerListenerMockRecorder
}

// MockDialerListenerMockRecorder is the mock recorder for MockDialerListener.
type MockDialerListenerMockRecorder struct {
	mock *MockDialerListener
}

// NewMockDialerListener creates a new mock instance.
func NewMockDialerListener(ctrl *gomock.Controller) *MockDialerListener {
	mock := &MockDialerListener{ctrl: ctrl}
	mock.recorder = &MockDialerListenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDialerListener) EXPECT() *MockDialerListenerMockRecorder {
	return m.recorder
}

// Dial mocks base method.
func (m *MockDialerListener) Dial(ctx context.Context, dst net.Destination) (net.Conn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dial", ctx, dst)
	ret0, _ := ret[0].(net.Conn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dial indicates an expected call of Dial.
func (mr *MockDialerListenerMockRecorder) Dial(ctx, dst interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dial", reflect.TypeOf((*MockDialerListener)(nil).Dial), ctx, dst)
}

// ListenPacket mocks base method.
func (m *MockDialerListener) ListenPacket(ctx context.Context, network, address string) (net.PacketConn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenPacket", ctx, network, address)
	ret0, _ := ret[0].(net.PacketConn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListenPacket indicates an expected call of ListenPacket.
func (mr *MockDialerListenerMockRecorder) ListenPacket(ctx, network, address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenPacket", reflect.TypeOf((*MockDialerListener)(nil).ListenPacket), ctx, network, address)
}

// MockUserValidator is a mock of UserValidator interface.
type MockUserValidator struct {
	ctrl     *gomock.Controller
	recorder *MockUserValidatorMockRecorder
}

// MockUserValidatorMockRecorder is the mock recorder for MockUserValidator.
type MockUserValidatorMockRecorder struct {
	mock *MockUserValidator
}

// NewMockUserValidator creates a new mock instance.
func NewMockUserValidator(ctrl *gomock.Controller) *MockUserValidator {
	mock := &MockUserValidator{ctrl: ctrl}
	mock.recorder = &MockUserValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserValidator) EXPECT() *MockUserValidatorMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockUserValidator) Validate(secret []byte) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", secret)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockUserValidatorMockRecorder) Validate(secret interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockUserValidator)(nil).Validate), secret)
}

// MockUser is a mock of User interface.
type MockUser struct {
	ctrl     *gomock.Controller
	recorder *MockUserMockRecorder
}

// MockUserMockRecorder is the mock recorder for MockUser.
type MockUserMockRecorder struct {
	mock *MockUser
}

// NewMockUser creates a new mock instance.
func NewMockUser(ctrl *gomock.Controller) *MockUser {
	mock := &MockUser{ctrl: ctrl}
	mock.recorder = &MockUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUser) EXPECT() *MockUserMockRecorder {
	return m.recorder
}

// Counter mocks base method.
func (m *MockUser) Counter() *atomic.Uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Counter")
	ret0, _ := ret[0].(*atomic.Uint64)
	return ret0
}

// Counter indicates an expected call of Counter.
func (mr *MockUserMockRecorder) Counter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Counter", reflect.TypeOf((*MockUser)(nil).Counter))
}

// Level mocks base method.
func (m *MockUser) Level() uint32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Level")
	ret0, _ := ret[0].(uint32)
	return ret0
}

// Level indicates an expected call of Level.
func (mr *MockUserMockRecorder) Level() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Level", reflect.TypeOf((*MockUser)(nil).Level))
}

// Secret mocks base method.
func (m *MockUser) Secret() uuid.UUID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Secret")
	ret0, _ := ret[0].(uuid.UUID)
	return ret0
}

// Secret indicates an expected call of Secret.
func (mr *MockUserMockRecorder) Secret() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Secret", reflect.TypeOf((*MockUser)(nil).Secret))
}

// Uid mocks base method.
func (m *MockUser) Uid() uuid.UUID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Uid")
	ret0, _ := ret[0].(uuid.UUID)
	return ret0
}

// Uid indicates an expected call of Uid.
func (mr *MockUserMockRecorder) Uid() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Uid", reflect.TypeOf((*MockUser)(nil).Uid))
}

// MockTunInfo is a mock of TunInfo interface.
type MockTunInfo struct {
	ctrl     *gomock.Controller
	recorder *MockTunInfoMockRecorder
}

// MockTunInfoMockRecorder is the mock recorder for MockTunInfo.
type MockTunInfoMockRecorder struct {
	mock *MockTunInfo
}

// NewMockTunInfo creates a new mock instance.
func NewMockTunInfo(ctrl *gomock.Controller) *MockTunInfo {
	mock := &MockTunInfo{ctrl: ctrl}
	mock.recorder = &MockTunInfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTunInfo) EXPECT() *MockTunInfoMockRecorder {
	return m.recorder
}

// ShouldBindDevice mocks base method.
func (m *MockTunInfo) ShouldBindDevice() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldBindDevice")
	ret0, _ := ret[0].(bool)
	return ret0
}

// ShouldBindDevice indicates an expected call of ShouldBindDevice.
func (mr *MockTunInfoMockRecorder) ShouldBindDevice() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldBindDevice", reflect.TypeOf((*MockTunInfo)(nil).ShouldBindDevice))
}

// TunDns mocks base method.
func (m *MockTunInfo) TunDns() []netip.Addr {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TunDns")
	ret0, _ := ret[0].([]netip.Addr)
	return ret0
}

// TunDns indicates an expected call of TunDns.
func (mr *MockTunInfoMockRecorder) TunDns() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TunDns", reflect.TypeOf((*MockTunInfo)(nil).TunDns))
}

// TunEnabled mocks base method.
func (m *MockTunInfo) TunEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TunEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// TunEnabled indicates an expected call of TunEnabled.
func (mr *MockTunInfoMockRecorder) TunEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TunEnabled", reflect.TypeOf((*MockTunInfo)(nil).TunEnabled))
}

// MockDefaultInterfaceInfo is a mock of DefaultInterfaceInfo interface.
type MockDefaultInterfaceInfo struct {
	ctrl     *gomock.Controller
	recorder *MockDefaultInterfaceInfoMockRecorder
}

// MockDefaultInterfaceInfoMockRecorder is the mock recorder for MockDefaultInterfaceInfo.
type MockDefaultInterfaceInfoMockRecorder struct {
	mock *MockDefaultInterfaceInfo
}

// NewMockDefaultInterfaceInfo creates a new mock instance.
func NewMockDefaultInterfaceInfo(ctrl *gomock.Controller) *MockDefaultInterfaceInfo {
	mock := &MockDefaultInterfaceInfo{ctrl: ctrl}
	mock.recorder = &MockDefaultInterfaceInfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDefaultInterfaceInfo) EXPECT() *MockDefaultInterfaceInfoMockRecorder {
	return m.recorder
}

// DefaultDns4 mocks base method.
func (m *MockDefaultInterfaceInfo) DefaultDns4() []netip.Addr {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultDns4")
	ret0, _ := ret[0].([]netip.Addr)
	return ret0
}

// DefaultDns4 indicates an expected call of DefaultDns4.
func (mr *MockDefaultInterfaceInfoMockRecorder) DefaultDns4() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultDns4", reflect.TypeOf((*MockDefaultInterfaceInfo)(nil).DefaultDns4))
}

// DefaultDns6 mocks base method.
func (m *MockDefaultInterfaceInfo) DefaultDns6() []netip.Addr {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultDns6")
	ret0, _ := ret[0].([]netip.Addr)
	return ret0
}

// DefaultDns6 indicates an expected call of DefaultDns6.
func (mr *MockDefaultInterfaceInfoMockRecorder) DefaultDns6() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultDns6", reflect.TypeOf((*MockDefaultInterfaceInfo)(nil).DefaultDns6))
}

// DefaultInterface4 mocks base method.
func (m *MockDefaultInterfaceInfo) DefaultInterface4() uint32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultInterface4")
	ret0, _ := ret[0].(uint32)
	return ret0
}

// DefaultInterface4 indicates an expected call of DefaultInterface4.
func (mr *MockDefaultInterfaceInfoMockRecorder) DefaultInterface4() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultInterface4", reflect.TypeOf((*MockDefaultInterfaceInfo)(nil).DefaultInterface4))
}

// DefaultInterface6 mocks base method.
func (m *MockDefaultInterfaceInfo) DefaultInterface6() uint32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultInterface6")
	ret0, _ := ret[0].(uint32)
	return ret0
}

// DefaultInterface6 indicates an expected call of DefaultInterface6.
func (mr *MockDefaultInterfaceInfoMockRecorder) DefaultInterface6() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultInterface6", reflect.TypeOf((*MockDefaultInterfaceInfo)(nil).DefaultInterface6))
}

// DefaultInterfaceName4 mocks base method.
func (m *MockDefaultInterfaceInfo) DefaultInterfaceName4() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultInterfaceName4")
	ret0, _ := ret[0].(string)
	return ret0
}

// DefaultInterfaceName4 indicates an expected call of DefaultInterfaceName4.
func (mr *MockDefaultInterfaceInfoMockRecorder) DefaultInterfaceName4() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultInterfaceName4", reflect.TypeOf((*MockDefaultInterfaceInfo)(nil).DefaultInterfaceName4))
}

// DefaultInterfaceName6 mocks base method.
func (m *MockDefaultInterfaceInfo) DefaultInterfaceName6() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultInterfaceName6")
	ret0, _ := ret[0].(string)
	return ret0
}

// DefaultInterfaceName6 indicates an expected call of DefaultInterfaceName6.
func (mr *MockDefaultInterfaceInfoMockRecorder) DefaultInterfaceName6() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultInterfaceName6", reflect.TypeOf((*MockDefaultInterfaceInfo)(nil).DefaultInterfaceName6))
}

// HasGlobalIPv6 mocks base method.
func (m *MockDefaultInterfaceInfo) HasGlobalIPv6() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasGlobalIPv6")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasGlobalIPv6 indicates an expected call of HasGlobalIPv6.
func (mr *MockDefaultInterfaceInfoMockRecorder) HasGlobalIPv6() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasGlobalIPv6", reflect.TypeOf((*MockDefaultInterfaceInfo)(nil).HasGlobalIPv6))
}

// Notify mocks base method.
func (m *MockDefaultInterfaceInfo) Notify() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Notify")
}

// Notify indicates an expected call of Notify.
func (mr *MockDefaultInterfaceInfoMockRecorder) Notify() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockDefaultInterfaceInfo)(nil).Notify))
}

// Register mocks base method.
func (m *MockDefaultInterfaceInfo) Register(observer i.DefaultInterfaceChangeObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", observer)
}

// Register indicates an expected call of Register.
func (mr *MockDefaultInterfaceInfoMockRecorder) Register(observer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockDefaultInterfaceInfo)(nil).Register), observer)
}

// SupportIPv6 mocks base method.
func (m *MockDefaultInterfaceInfo) SupportIPv6() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportIPv6")
	ret0, _ := ret[0].(int)
	return ret0
}

// SupportIPv6 indicates an expected call of SupportIPv6.
func (mr *MockDefaultInterfaceInfoMockRecorder) SupportIPv6() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportIPv6", reflect.TypeOf((*MockDefaultInterfaceInfo)(nil).SupportIPv6))
}

// Unregister mocks base method.
func (m *MockDefaultInterfaceInfo) Unregister(observer i.DefaultInterfaceChangeObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unregister", observer)
}

// Unregister indicates an expected call of Unregister.
func (mr *MockDefaultInterfaceInfoMockRecorder) Unregister(observer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unregister", reflect.TypeOf((*MockDefaultInterfaceInfo)(nil).Unregister), observer)
}

// MockDefaultInterfaceChangeSubject is a mock of DefaultInterfaceChangeSubject interface.
type MockDefaultInterfaceChangeSubject struct {
	ctrl     *gomock.Controller
	recorder *MockDefaultInterfaceChangeSubjectMockRecorder
}

// MockDefaultInterfaceChangeSubjectMockRecorder is the mock recorder for MockDefaultInterfaceChangeSubject.
type MockDefaultInterfaceChangeSubjectMockRecorder struct {
	mock *MockDefaultInterfaceChangeSubject
}

// NewMockDefaultInterfaceChangeSubject creates a new mock instance.
func NewMockDefaultInterfaceChangeSubject(ctrl *gomock.Controller) *MockDefaultInterfaceChangeSubject {
	mock := &MockDefaultInterfaceChangeSubject{ctrl: ctrl}
	mock.recorder = &MockDefaultInterfaceChangeSubjectMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDefaultInterfaceChangeSubject) EXPECT() *MockDefaultInterfaceChangeSubjectMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockDefaultInterfaceChangeSubject) Notify() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Notify")
}

// Notify indicates an expected call of Notify.
func (mr *MockDefaultInterfaceChangeSubjectMockRecorder) Notify() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockDefaultInterfaceChangeSubject)(nil).Notify))
}

// Register mocks base method.
func (m *MockDefaultInterfaceChangeSubject) Register(observer i.DefaultInterfaceChangeObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", observer)
}

// Register indicates an expected call of Register.
func (mr *MockDefaultInterfaceChangeSubjectMockRecorder) Register(observer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockDefaultInterfaceChangeSubject)(nil).Register), observer)
}

// Unregister mocks base method.
func (m *MockDefaultInterfaceChangeSubject) Unregister(observer i.DefaultInterfaceChangeObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unregister", observer)
}

// Unregister indicates an expected call of Unregister.
func (mr *MockDefaultInterfaceChangeSubjectMockRecorder) Unregister(observer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unregister", reflect.TypeOf((*MockDefaultInterfaceChangeSubject)(nil).Unregister), observer)
}

// MockDefaultInterfaceChangeObserver is a mock of DefaultInterfaceChangeObserver interface.
type MockDefaultInterfaceChangeObserver struct {
	ctrl     *gomock.Controller
	recorder *MockDefaultInterfaceChangeObserverMockRecorder
}

// MockDefaultInterfaceChangeObserverMockRecorder is the mock recorder for MockDefaultInterfaceChangeObserver.
type MockDefaultInterfaceChangeObserverMockRecorder struct {
	mock *MockDefaultInterfaceChangeObserver
}

// NewMockDefaultInterfaceChangeObserver creates a new mock instance.
func NewMockDefaultInterfaceChangeObserver(ctrl *gomock.Controller) *MockDefaultInterfaceChangeObserver {
	mock := &MockDefaultInterfaceChangeObserver{ctrl: ctrl}
	mock.recorder = &MockDefaultInterfaceChangeObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDefaultInterfaceChangeObserver) EXPECT() *MockDefaultInterfaceChangeObserverMockRecorder {
	return m.recorder
}

// OnDefaultInterfaceChanged mocks base method.
func (m *MockDefaultInterfaceChangeObserver) OnDefaultInterfaceChanged() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnDefaultInterfaceChanged")
}

// OnDefaultInterfaceChanged indicates an expected call of OnDefaultInterfaceChanged.
func (mr *MockDefaultInterfaceChangeObserverMockRecorder) OnDefaultInterfaceChanged() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnDefaultInterfaceChanged", reflect.TypeOf((*MockDefaultInterfaceChangeObserver)(nil).OnDefaultInterfaceChanged))
}

// MockIPv6SupportChangeSubject is a mock of IPv6SupportChangeSubject interface.
type MockIPv6SupportChangeSubject struct {
	ctrl     *gomock.Controller
	recorder *MockIPv6SupportChangeSubjectMockRecorder
}

// MockIPv6SupportChangeSubjectMockRecorder is the mock recorder for MockIPv6SupportChangeSubject.
type MockIPv6SupportChangeSubjectMockRecorder struct {
	mock *MockIPv6SupportChangeSubject
}

// NewMockIPv6SupportChangeSubject creates a new mock instance.
func NewMockIPv6SupportChangeSubject(ctrl *gomock.Controller) *MockIPv6SupportChangeSubject {
	mock := &MockIPv6SupportChangeSubject{ctrl: ctrl}
	mock.recorder = &MockIPv6SupportChangeSubjectMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPv6SupportChangeSubject) EXPECT() *MockIPv6SupportChangeSubjectMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockIPv6SupportChangeSubject) Notify() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Notify")
}

// Notify indicates an expected call of Notify.
func (mr *MockIPv6SupportChangeSubjectMockRecorder) Notify() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockIPv6SupportChangeSubject)(nil).Notify))
}

// Register mocks base method.
func (m *MockIPv6SupportChangeSubject) Register(observer i.IPv6SupportChangeObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", observer)
}

// Register indicates an expected call of Register.
func (mr *MockIPv6SupportChangeSubjectMockRecorder) Register(observer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockIPv6SupportChangeSubject)(nil).Register), observer)
}

// Unregister mocks base method.
func (m *MockIPv6SupportChangeSubject) Unregister(observer i.IPv6SupportChangeObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unregister", observer)
}

// Unregister indicates an expected call of Unregister.
func (mr *MockIPv6SupportChangeSubjectMockRecorder) Unregister(observer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unregister", reflect.TypeOf((*MockIPv6SupportChangeSubject)(nil).Unregister), observer)
}

// MockIPv6SupportChangeObserver is a mock of IPv6SupportChangeObserver interface.
type MockIPv6SupportChangeObserver struct {
	ctrl     *gomock.Controller
	recorder *MockIPv6SupportChangeObserverMockRecorder
}

// MockIPv6SupportChangeObserverMockRecorder is the mock recorder for MockIPv6SupportChangeObserver.
type MockIPv6SupportChangeObserverMockRecorder struct {
	mock *MockIPv6SupportChangeObserver
}

// NewMockIPv6SupportChangeObserver creates a new mock instance.
func NewMockIPv6SupportChangeObserver(ctrl *gomock.Controller) *MockIPv6SupportChangeObserver {
	mock := &MockIPv6SupportChangeObserver{ctrl: ctrl}
	mock.recorder = &MockIPv6SupportChangeObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPv6SupportChangeObserver) EXPECT() *MockIPv6SupportChangeObserverMockRecorder {
	return m.recorder
}

// OnIPv6SupportChanged mocks base method.
func (m *MockIPv6SupportChangeObserver) OnIPv6SupportChanged() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnIPv6SupportChanged")
}

// OnIPv6SupportChanged indicates an expected call of OnIPv6SupportChanged.
func (mr *MockIPv6SupportChangeObserverMockRecorder) OnIPv6SupportChanged() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnIPv6SupportChanged", reflect.TypeOf((*MockIPv6SupportChangeObserver)(nil).OnIPv6SupportChanged))
}

// MockProxyServerProcessor is a mock of ProxyServerProcessor interface.
type MockProxyServerProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockProxyServerProcessorMockRecorder
}

// MockProxyServerProcessorMockRecorder is the mock recorder for MockProxyServerProcessor.
type MockProxyServerProcessorMockRecorder struct {
	mock *MockProxyServerProcessor
}

// NewMockProxyServerProcessor creates a new mock instance.
func NewMockProxyServerProcessor(ctrl *gomock.Controller) *MockProxyServerProcessor {
	mock := &MockProxyServerProcessor{ctrl: ctrl}
	mock.recorder = &MockProxyServerProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProxyServerProcessor) EXPECT() *MockProxyServerProcessorMockRecorder {
	return m.recorder
}

// ProcessConn mocks base method.
func (m *MockProxyServerProcessor) ProcessConn(ctx context.Context, conn net.Conn) (chan interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessConn", ctx, conn)
	ret0, _ := ret[0].(chan interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessConn indicates an expected call of ProcessConn.
func (mr *MockProxyServerProcessorMockRecorder) ProcessConn(ctx, conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessConn", reflect.TypeOf((*MockProxyServerProcessor)(nil).ProcessConn), ctx, conn)
}

// MockProxyPacketConn is a mock of ProxyPacketConn interface.
type MockProxyPacketConn struct {
	ctrl     *gomock.Controller
	recorder *MockProxyPacketConnMockRecorder
}

// MockProxyPacketConnMockRecorder is the mock recorder for MockProxyPacketConn.
type MockProxyPacketConnMockRecorder struct {
	mock *MockProxyPacketConn
}

// NewMockProxyPacketConn creates a new mock instance.
func NewMockProxyPacketConn(ctrl *gomock.Controller) *MockProxyPacketConn {
	mock := &MockProxyPacketConn{ctrl: ctrl}
	mock.recorder = &MockProxyPacketConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProxyPacketConn) EXPECT() *MockProxyPacketConnMockRecorder {
	return m.recorder
}

// ReadPacket mocks base method.
func (m *MockProxyPacketConn) ReadPacket() (*udp.Packet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadPacket")
	ret0, _ := ret[0].(*udp.Packet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadPacket indicates an expected call of ReadPacket.
func (mr *MockProxyPacketConnMockRecorder) ReadPacket() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadPacket", reflect.TypeOf((*MockProxyPacketConn)(nil).ReadPacket))
}

// User mocks base method.
func (m *MockProxyPacketConn) User() i.User {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "User")
	ret0, _ := ret[0].(i.User)
	return ret0
}

// User indicates an expected call of User.
func (mr *MockProxyPacketConnMockRecorder) User() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*MockProxyPacketConn)(nil).User))
}

// WritePacket mocks base method.
func (m *MockProxyPacketConn) WritePacket(p *udp.Packet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WritePacket", p)
	ret0, _ := ret[0].(error)
	return ret0
}

// WritePacket indicates an expected call of WritePacket.
func (mr *MockProxyPacketConnMockRecorder) WritePacket(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WritePacket", reflect.TypeOf((*MockProxyPacketConn)(nil).WritePacket), p)
}

// MockProxyClientProcessor is a mock of ProxyClientProcessor interface.
type MockProxyClientProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockProxyClientProcessorMockRecorder
}

// MockProxyClientProcessorMockRecorder is the mock recorder for MockProxyClientProcessor.
type MockProxyClientProcessorMockRecorder struct {
	mock *MockProxyClientProcessor
}

// NewMockProxyClientProcessor creates a new mock instance.
func NewMockProxyClientProcessor(ctrl *gomock.Controller) *MockProxyClientProcessor {
	mock := &MockProxyClientProcessor{ctrl: ctrl}
	mock.recorder = &MockProxyClientProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProxyClientProcessor) EXPECT() *MockProxyClientProcessorMockRecorder {
	return m.recorder
}

// ProcessConn mocks base method.
func (m *MockProxyClientProcessor) ProcessConn(ctx context.Context, conn net.Conn) (net.Conn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessConn", ctx, conn)
	ret0, _ := ret[0].(net.Conn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessConn indicates an expected call of ProcessConn.
func (mr *MockProxyClientProcessorMockRecorder) ProcessConn(ctx, conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessConn", reflect.TypeOf((*MockProxyClientProcessor)(nil).ProcessConn), ctx, conn)
}

// ProcessPacketConn mocks base method.
func (m *MockProxyClientProcessor) ProcessPacketConn(ctx context.Context, conn net.PacketConn) (net.PacketConn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessPacketConn", ctx, conn)
	ret0, _ := ret[0].(net.PacketConn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessPacketConn indicates an expected call of ProcessPacketConn.
func (mr *MockProxyClientProcessorMockRecorder) ProcessPacketConn(ctx, conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessPacketConn", reflect.TypeOf((*MockProxyClientProcessor)(nil).ProcessPacketConn), ctx, conn)
}

// MockIPResolver is a mock of IPResolver interface.
type MockIPResolver struct {
	ctrl     *gomock.Controller
	recorder *MockIPResolverMockRecorder
}

// MockIPResolverMockRecorder is the mock recorder for MockIPResolver.
type MockIPResolverMockRecorder struct {
	mock *MockIPResolver
}

// NewMockIPResolver creates a new mock instance.
func NewMockIPResolver(ctrl *gomock.Controller) *MockIPResolver {
	mock := &MockIPResolver{ctrl: ctrl}
	mock.recorder = &MockIPResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPResolver) EXPECT() *MockIPResolverMockRecorder {
	return m.recorder
}

// LookupIP mocks base method.
func (m *MockIPResolver) LookupIP(ctx context.Context, domain string) ([]net.IP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupIP", ctx, domain)
	ret0, _ := ret[0].([]net.IP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupIP indicates an expected call of LookupIP.
func (mr *MockIPResolverMockRecorder) LookupIP(ctx, domain interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupIP", reflect.TypeOf((*MockIPResolver)(nil).LookupIP), ctx, domain)
}

// LookupIPv4 mocks base method.
func (m *MockIPResolver) LookupIPv4(ctx context.Context, domain string) ([]net.IP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupIPv4", ctx, domain)
	ret0, _ := ret[0].([]net.IP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupIPv4 indicates an expected call of LookupIPv4.
func (mr *MockIPResolverMockRecorder) LookupIPv4(ctx, domain interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupIPv4", reflect.TypeOf((*MockIPResolver)(nil).LookupIPv4), ctx, domain)
}

// LookupIPv6 mocks base method.
func (m *MockIPResolver) LookupIPv6(ctx context.Context, domain string) ([]net.IP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupIPv6", ctx, domain)
	ret0, _ := ret[0].([]net.IP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupIPv6 indicates an expected call of LookupIPv6.
func (mr *MockIPResolverMockRecorder) LookupIPv6(ctx, domain interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupIPv6", reflect.TypeOf((*MockIPResolver)(nil).LookupIPv6), ctx, domain)
}

// MockFakeDnsPool is a mock of FakeDnsPool interface.
type MockFakeDnsPool struct {
	ctrl     *gomock.Controller
	recorder *MockFakeDnsPoolMockRecorder
}

// MockFakeDnsPoolMockRecorder is the mock recorder for MockFakeDnsPool.
type MockFakeDnsPoolMockRecorder struct {
	mock *MockFakeDnsPool
}

// NewMockFakeDnsPool creates a new mock instance.
func NewMockFakeDnsPool(ctrl *gomock.Controller) *MockFakeDnsPool {
	mock := &MockFakeDnsPool{ctrl: ctrl}
	mock.recorder = &MockFakeDnsPoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFakeDnsPool) EXPECT() *MockFakeDnsPoolMockRecorder {
	return m.recorder
}

// GetDomainFromFakeDNS mocks base method.
func (m *MockFakeDnsPool) GetDomainFromFakeDNS(ip net.Address) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDomainFromFakeDNS", ip)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDomainFromFakeDNS indicates an expected call of GetDomainFromFakeDNS.
func (mr *MockFakeDnsPoolMockRecorder) GetDomainFromFakeDNS(ip interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDomainFromFakeDNS", reflect.TypeOf((*MockFakeDnsPool)(nil).GetDomainFromFakeDNS), ip)
}

// IsIPInIPPool mocks base method.
func (m *MockFakeDnsPool) IsIPInIPPool(ip net.Address) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsIPInIPPool", ip)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsIPInIPPool indicates an expected call of IsIPInIPPool.
func (mr *MockFakeDnsPoolMockRecorder) IsIPInIPPool(ip interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsIPInIPPool", reflect.TypeOf((*MockFakeDnsPool)(nil).IsIPInIPPool), ip)
}

// MockUint64Counter is a mock of Uint64Counter interface.
type MockUint64Counter struct {
	ctrl     *gomock.Controller
	recorder *MockUint64CounterMockRecorder
}

// MockUint64CounterMockRecorder is the mock recorder for MockUint64Counter.
type MockUint64CounterMockRecorder struct {
	mock *MockUint64Counter
}

// NewMockUint64Counter creates a new mock instance.
func NewMockUint64Counter(ctrl *gomock.Controller) *MockUint64Counter {
	mock := &MockUint64Counter{ctrl: ctrl}
	mock.recorder = &MockUint64CounterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUint64Counter) EXPECT() *MockUint64CounterMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockUint64Counter) Add(v uint64) uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", v)
	ret0, _ := ret[0].(uint64)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockUint64CounterMockRecorder) Add(v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockUint64Counter)(nil).Add), v)
}

// Load mocks base method.
func (m *MockUint64Counter) Load() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// Load indicates an expected call of Load.
func (mr *MockUint64CounterMockRecorder) Load() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockUint64Counter)(nil).Load))
}

// MockOutboundManager is a mock of OutboundManager interface.
type MockOutboundManager struct {
	ctrl     *gomock.Controller
	recorder *MockOutboundManagerMockRecorder
}

// MockOutboundManagerMockRecorder is the mock recorder for MockOutboundManager.
type MockOutboundManagerMockRecorder struct {
	mock *MockOutboundManager
}

// NewMockOutboundManager creates a new mock instance.
func NewMockOutboundManager(ctrl *gomock.Controller) *MockOutboundManager {
	mock := &MockOutboundManager{ctrl: ctrl}
	mock.recorder = &MockOutboundManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboundManager) EXPECT() *MockOutboundManagerMockRecorder {
	return m.recorder
}

// GetAllHandlers mocks base method.
func (m *MockOutboundManager) GetAllHandlers() []i.Outbound {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllHandlers")
	ret0, _ := ret[0].([]i.Outbound)
	return ret0
}

// GetAllHandlers indicates an expected call of GetAllHandlers.
func (mr *MockOutboundManagerMockRecorder) GetAllHandlers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllHandlers", reflect.TypeOf((*MockOutboundManager)(nil).GetAllHandlers))
}

// GetHandler mocks base method.
func (m *MockOutboundManager) GetHandler(tag string) i.Outbound {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHandler", tag)
	ret0, _ := ret[0].(i.Outbound)
	return ret0
}

// GetHandler indicates an expected call of GetHandler.
func (mr *MockOutboundManagerMockRecorder) GetHandler(tag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHandler", reflect.TypeOf((*MockOutboundManager)(nil).GetHandler), tag)
}

// MockRouter is a mock of Router interface.
type MockRouter struct {
	ctrl     *gomock.Controller
	recorder *MockRouterMockRecorder
}

// MockRouterMockRecorder is the mock recorder for MockRouter.
type MockRouterMockRecorder struct {
	mock *MockRouter
}

// NewMockRouter creates a new mock instance.
func NewMockRouter(ctrl *gomock.Controller) *MockRouter {
	mock := &MockRouter{ctrl: ctrl}
	mock.recorder = &MockRouterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRouter) EXPECT() *MockRouterMockRecorder {
	return m.recorder
}

// PickHandler mocks base method.
func (m *MockRouter) PickHandler(ctx context.Context, si *session.Info) (i.Outbound, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PickHandler", ctx, si)
	ret0, _ := ret[0].(i.Outbound)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PickHandler indicates an expected call of PickHandler.
func (mr *MockRouterMockRecorder) PickHandler(ctx, si interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PickHandler", reflect.TypeOf((*MockRouter)(nil).PickHandler), ctx, si)
}

// MockIpToDomain is a mock of IpToDomain interface.
type MockIpToDomain struct {
	ctrl     *gomock.Controller
	recorder *MockIpToDomainMockRecorder
}

// MockIpToDomainMockRecorder is the mock recorder for MockIpToDomain.
type MockIpToDomainMockRecorder struct {
	mock *MockIpToDomain
}

// NewMockIpToDomain creates a new mock instance.
func NewMockIpToDomain(ctrl *gomock.Controller) *MockIpToDomain {
	mock := &MockIpToDomain{ctrl: ctrl}
	mock.recorder = &MockIpToDomainMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIpToDomain) EXPECT() *MockIpToDomainMockRecorder {
	return m.recorder
}

// GetDomain mocks base method.
func (m *MockIpToDomain) GetDomain(ip net.IP) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDomain", ip)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDomain indicates an expected call of GetDomain.
func (mr *MockIpToDomainMockRecorder) GetDomain(ip interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDomain", reflect.TypeOf((*MockIpToDomain)(nil).GetDomain), ip)
}

// MockHandlerErrorObserver is a mock of HandlerErrorObserver interface.
type MockHandlerErrorObserver struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerErrorObserverMockRecorder
}

// MockHandlerErrorObserverMockRecorder is the mock recorder for MockHandlerErrorObserver.
type MockHandlerErrorObserverMockRecorder struct {
	mock *MockHandlerErrorObserver
}

// NewMockHandlerErrorObserver creates a new mock instance.
func NewMockHandlerErrorObserver(ctrl *gomock.Controller) *MockHandlerErrorObserver {
	mock := &MockHandlerErrorObserver{ctrl: ctrl}
	mock.recorder = &MockHandlerErrorObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandlerErrorObserver) EXPECT() *MockHandlerErrorObserverMockRecorder {
	return m.recorder
}

// OnHandlerError mocks base method.
func (m *MockHandlerErrorObserver) OnHandlerError(tag string, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnHandlerError", tag, err)
}

// OnHandlerError indicates an expected call of OnHandlerError.
func (mr *MockHandlerErrorObserverMockRecorder) OnHandlerError(tag, err interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnHandlerError", reflect.TypeOf((*MockHandlerErrorObserver)(nil).OnHandlerError), tag, err)
}

// MockPortSelector is a mock of PortSelector interface.
type MockPortSelector struct {
	ctrl     *gomock.Controller
	recorder *MockPortSelectorMockRecorder
}

// MockPortSelectorMockRecorder is the mock recorder for MockPortSelector.
type MockPortSelectorMockRecorder struct {
	mock *MockPortSelector
}

// NewMockPortSelector creates a new mock instance.
func NewMockPortSelector(ctrl *gomock.Controller) *MockPortSelector {
	mock := &MockPortSelector{ctrl: ctrl}
	mock.recorder = &MockPortSelectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPortSelector) EXPECT() *MockPortSelectorMockRecorder {
	return m.recorder
}

// SelectPort mocks base method.
func (m *MockPortSelector) SelectPort() (uint16, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectPort")
	ret0, _ := ret[0].(uint16)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectPort indicates an expected call of SelectPort.
func (mr *MockPortSelectorMockRecorder) SelectPort() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectPort", reflect.TypeOf((*MockPortSelector)(nil).SelectPort))
}
