// Code generated by MockGen. DO NOT EDIT.
// Source: core\interfaces\extension\tun_monitor.go

// Package mocks is a generated GoMock package.
package mocks

import (
	netip "net/netip"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockInterfaceMonitor is a mock of InterfaceMonitor interface.
type MockInterfaceMonitor struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMonitorMockRecorder
}

// MockInterfaceMonitorMockRecorder is the mock recorder for MockInterfaceMonitor.
type MockInterfaceMonitorMockRecorder struct {
	mock *MockInterfaceMonitor
}

// NewMockInterfaceMonitor creates a new mock instance.
func NewMockInterfaceMonitor(ctrl *gomock.Controller) *MockInterfaceMonitor {
	mock := &MockInterfaceMonitor{ctrl: ctrl}
	mock.recorder = &MockInterfaceMonitorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterfaceMonitor) EXPECT() *MockInterfaceMonitorMockRecorder {
	return m.recorder
}

// DefaultDnsServerAddr mocks base method.
func (m *MockInterfaceMonitor) DefaultDnsServerAddr() []netip.Addr {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultDnsServerAddr")
	ret0, _ := ret[0].([]netip.Addr)
	return ret0
}

// DefaultDnsServerAddr indicates an expected call of DefaultDnsServerAddr.
func (mr *MockInterfaceMonitorMockRecorder) DefaultDnsServerAddr() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultDnsServerAddr", reflect.TypeOf((*MockInterfaceMonitor)(nil).DefaultDnsServerAddr))
}

// DefaultInterfaceName4 mocks base method.
func (m *MockInterfaceMonitor) DefaultInterfaceName4() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultInterfaceName4")
	ret0, _ := ret[0].(string)
	return ret0
}

// DefaultInterfaceName4 indicates an expected call of DefaultInterfaceName4.
func (mr *MockInterfaceMonitorMockRecorder) DefaultInterfaceName4() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultInterfaceName4", reflect.TypeOf((*MockInterfaceMonitor)(nil).DefaultInterfaceName4))
}

// DefaultInterfaceName6 mocks base method.
func (m *MockInterfaceMonitor) DefaultInterfaceName6() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultInterfaceName6")
	ret0, _ := ret[0].(string)
	return ret0
}

// DefaultInterfaceName6 indicates an expected call of DefaultInterfaceName6.
func (mr *MockInterfaceMonitorMockRecorder) DefaultInterfaceName6() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultInterfaceName6", reflect.TypeOf((*MockInterfaceMonitor)(nil).DefaultInterfaceName6))
}

// TunEnabled mocks base method.
func (m *MockInterfaceMonitor) TunEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TunEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// TunEnabled indicates an expected call of TunEnabled.
func (mr *MockInterfaceMonitorMockRecorder) TunEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TunEnabled", reflect.TypeOf((*MockInterfaceMonitor)(nil).TunEnabled))
}
