// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: app/grpcservice/grpc.proto

package grpcservice

import (
	geo1 "buf.build/gen/go/vvvvv/vx/protocolbuffers/go/vx/common/geo"
	geo "buf.build/gen/go/vvvvv/vx/protocolbuffers/go/vx/geo"
	inbound "buf.build/gen/go/vvvvv/vx/protocolbuffers/go/vx/inbound"
	outbound "buf.build/gen/go/vvvvv/vx/protocolbuffers/go/vx/outbound"
	router "buf.build/gen/go/vvvvv/vx/protocolbuffers/go/vx/router"
	userlogger "github.com/5vnetwork/vx-core/app/userlogger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RttTestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RttTestRequest) Reset() {
	*x = RttTestRequest{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RttTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RttTestRequest) ProtoMessage() {}

func (x *RttTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RttTestRequest.ProtoReflect.Descriptor instead.
func (*RttTestRequest) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *RttTestRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *RttTestRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type RttTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ping          uint32                 `protobuf:"varint,1,opt,name=ping,proto3" json:"ping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RttTestResponse) Reset() {
	*x = RttTestResponse{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RttTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RttTestResponse) ProtoMessage() {}

func (x *RttTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RttTestResponse.ProtoReflect.Descriptor instead.
func (*RttTestResponse) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *RttTestResponse) GetPing() uint32 {
	if x != nil {
		return x.Ping
	}
	return 0
}

type Receipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{2}
}

type CommunicateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommunicateRequest) Reset() {
	*x = CommunicateRequest{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommunicateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunicateRequest) ProtoMessage() {}

func (x *CommunicateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunicateRequest.ProtoReflect.Descriptor instead.
func (*CommunicateRequest) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{3}
}

type CommunicateMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*CommunicateMessage_HandlerError
	//	*CommunicateMessage_SubscriptionUpdate
	//	*CommunicateMessage_HandlerBeingUsed
	//	*CommunicateMessage_HandlerUpdated
	Message       isCommunicateMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommunicateMessage) Reset() {
	*x = CommunicateMessage{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommunicateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunicateMessage) ProtoMessage() {}

func (x *CommunicateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunicateMessage.ProtoReflect.Descriptor instead.
func (*CommunicateMessage) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *CommunicateMessage) GetMessage() isCommunicateMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *CommunicateMessage) GetHandlerError() *HandlerError {
	if x != nil {
		if x, ok := x.Message.(*CommunicateMessage_HandlerError); ok {
			return x.HandlerError
		}
	}
	return nil
}

func (x *CommunicateMessage) GetSubscriptionUpdate() *SubscriptionUpdated {
	if x != nil {
		if x, ok := x.Message.(*CommunicateMessage_SubscriptionUpdate); ok {
			return x.SubscriptionUpdate
		}
	}
	return nil
}

func (x *CommunicateMessage) GetHandlerBeingUsed() *HandlerBeingUsed {
	if x != nil {
		if x, ok := x.Message.(*CommunicateMessage_HandlerBeingUsed); ok {
			return x.HandlerBeingUsed
		}
	}
	return nil
}

func (x *CommunicateMessage) GetHandlerUpdated() *HandlerUpdated {
	if x != nil {
		if x, ok := x.Message.(*CommunicateMessage_HandlerUpdated); ok {
			return x.HandlerUpdated
		}
	}
	return nil
}

type isCommunicateMessage_Message interface {
	isCommunicateMessage_Message()
}

type CommunicateMessage_HandlerError struct {
	HandlerError *HandlerError `protobuf:"bytes,1,opt,name=handler_error,json=handlerError,proto3,oneof"`
}

type CommunicateMessage_SubscriptionUpdate struct {
	SubscriptionUpdate *SubscriptionUpdated `protobuf:"bytes,2,opt,name=subscription_update,json=subscriptionUpdate,proto3,oneof"`
}

type CommunicateMessage_HandlerBeingUsed struct {
	HandlerBeingUsed *HandlerBeingUsed `protobuf:"bytes,3,opt,name=handler_being_used,json=handlerBeingUsed,proto3,oneof"`
}

type CommunicateMessage_HandlerUpdated struct {
	HandlerUpdated *HandlerUpdated `protobuf:"bytes,4,opt,name=handler_updated,json=handlerUpdated,proto3,oneof"`
}

func (*CommunicateMessage_HandlerError) isCommunicateMessage_Message() {}

func (*CommunicateMessage_SubscriptionUpdate) isCommunicateMessage_Message() {}

func (*CommunicateMessage_HandlerBeingUsed) isCommunicateMessage_Message() {}

func (*CommunicateMessage_HandlerUpdated) isCommunicateMessage_Message() {}

type HandlerError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandlerError) Reset() {
	*x = HandlerError{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlerError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlerError) ProtoMessage() {}

func (x *HandlerError) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlerError.ProtoReflect.Descriptor instead.
func (*HandlerError) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{5}
}

func (x *HandlerError) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *HandlerError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HandlerBeingUsed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      string                 `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandlerBeingUsed) Reset() {
	*x = HandlerBeingUsed{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlerBeingUsed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlerBeingUsed) ProtoMessage() {}

func (x *HandlerBeingUsed) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlerBeingUsed.ProtoReflect.Descriptor instead.
func (*HandlerBeingUsed) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{6}
}

func (x *HandlerBeingUsed) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *HandlerBeingUsed) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type HandlerUpdated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandlerUpdated) Reset() {
	*x = HandlerUpdated{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlerUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlerUpdated) ProtoMessage() {}

func (x *HandlerUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlerUpdated.ProtoReflect.Descriptor instead.
func (*HandlerUpdated) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{7}
}

func (x *HandlerUpdated) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SubscriptionUpdated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionUpdated) Reset() {
	*x = SubscriptionUpdated{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionUpdated) ProtoMessage() {}

func (x *SubscriptionUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionUpdated.ProtoReflect.Descriptor instead.
func (*SubscriptionUpdated) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{8}
}

// inbound
type AddInboundRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	HandlerConfig *inbound.ProxyInboundConfig `protobuf:"bytes,1,opt,name=handler_config,json=handlerConfig,proto3" json:"handler_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddInboundRequest) Reset() {
	*x = AddInboundRequest{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddInboundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddInboundRequest) ProtoMessage() {}

func (x *AddInboundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddInboundRequest.ProtoReflect.Descriptor instead.
func (*AddInboundRequest) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{9}
}

func (x *AddInboundRequest) GetHandlerConfig() *inbound.ProxyInboundConfig {
	if x != nil {
		return x.HandlerConfig
	}
	return nil
}

type AddInboundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddInboundResponse) Reset() {
	*x = AddInboundResponse{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddInboundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddInboundResponse) ProtoMessage() {}

func (x *AddInboundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddInboundResponse.ProtoReflect.Descriptor instead.
func (*AddInboundResponse) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{10}
}

type RemoveInboundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveInboundRequest) Reset() {
	*x = RemoveInboundRequest{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveInboundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveInboundRequest) ProtoMessage() {}

func (x *RemoveInboundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveInboundRequest.ProtoReflect.Descriptor instead.
func (*RemoveInboundRequest) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveInboundRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type RemoveInboundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveInboundResponse) Reset() {
	*x = RemoveInboundResponse{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveInboundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveInboundResponse) ProtoMessage() {}

func (x *RemoveInboundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveInboundResponse.ProtoReflect.Descriptor instead.
func (*RemoveInboundResponse) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{12}
}

type OutboundStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Up    uint64                 `protobuf:"varint,1,opt,name=up,proto3" json:"up,omitempty"`
	Down  uint64                 `protobuf:"varint,2,opt,name=down,proto3" json:"down,omitempty"`
	// download
	Rate uint64 `protobuf:"varint,3,opt,name=rate,proto3" json:"rate,omitempty"`
	Ping uint64 `protobuf:"varint,4,opt,name=ping,proto3" json:"ping,omitempty"`
	Id   string `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	// seconds
	Interval      float32 `protobuf:"fixed32,6,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboundStats) Reset() {
	*x = OutboundStats{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundStats) ProtoMessage() {}

func (x *OutboundStats) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundStats.ProtoReflect.Descriptor instead.
func (*OutboundStats) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{13}
}

func (x *OutboundStats) GetUp() uint64 {
	if x != nil {
		return x.Up
	}
	return 0
}

func (x *OutboundStats) GetDown() uint64 {
	if x != nil {
		return x.Down
	}
	return 0
}

func (x *OutboundStats) GetRate() uint64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *OutboundStats) GetPing() uint64 {
	if x != nil {
		return x.Ping
	}
	return 0
}

func (x *OutboundStats) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OutboundStats) GetInterval() float32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interval      uint32                 `protobuf:"varint,1,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{14}
}

func (x *GetStatsRequest) GetInterval() uint32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*OutboundStats       `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	Connections   int32                  `protobuf:"varint,2,opt,name=connections,proto3" json:"connections,omitempty"`
	Memory        uint64                 `protobuf:"varint,3,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{15}
}

func (x *StatsResponse) GetStats() []*OutboundStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *StatsResponse) GetConnections() int32 {
	if x != nil {
		return x.Connections
	}
	return 0
}

func (x *StatsResponse) GetMemory() uint64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

type SetOutboundHandlerSpeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Speed         int32                  `protobuf:"varint,2,opt,name=speed,proto3" json:"speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOutboundHandlerSpeedRequest) Reset() {
	*x = SetOutboundHandlerSpeedRequest{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOutboundHandlerSpeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOutboundHandlerSpeedRequest) ProtoMessage() {}

func (x *SetOutboundHandlerSpeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOutboundHandlerSpeedRequest.ProtoReflect.Descriptor instead.
func (*SetOutboundHandlerSpeedRequest) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{16}
}

func (x *SetOutboundHandlerSpeedRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *SetOutboundHandlerSpeedRequest) GetSpeed() int32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type SetOutboundHandlerSpeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOutboundHandlerSpeedResponse) Reset() {
	*x = SetOutboundHandlerSpeedResponse{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOutboundHandlerSpeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOutboundHandlerSpeedResponse) ProtoMessage() {}

func (x *SetOutboundHandlerSpeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOutboundHandlerSpeedResponse.ProtoReflect.Descriptor instead.
func (*SetOutboundHandlerSpeedResponse) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{17}
}

type SelectedHandlersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectedHandlersRequest) Reset() {
	*x = SelectedHandlersRequest{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectedHandlersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectedHandlersRequest) ProtoMessage() {}

func (x *SelectedHandlersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectedHandlersRequest.ProtoReflect.Descriptor instead.
func (*SelectedHandlersRequest) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{18}
}

type SelectedHandlersResponse struct {
	state            protoimpl.MessageState                       `protogen:"open.v1"`
	SelectedHandlers map[string]*SelectedHandlersResponse_Strings `protobuf:"bytes,1,rep,name=selected_handlers,json=selectedHandlers,proto3" json:"selected_handlers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SelectedHandlersResponse) Reset() {
	*x = SelectedHandlersResponse{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectedHandlersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectedHandlersResponse) ProtoMessage() {}

func (x *SelectedHandlersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectedHandlersResponse.ProtoReflect.Descriptor instead.
func (*SelectedHandlersResponse) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{19}
}

func (x *SelectedHandlersResponse) GetSelectedHandlers() map[string]*SelectedHandlersResponse_Strings {
	if x != nil {
		return x.SelectedHandlers
	}
	return nil
}

// log
// message ChangeLogLevelRequest { x.Level level = 1; }
// message ChangeLogLevelResponse {}
// message LogStreamRequest {}
// message LogMessage { string message = 1; }
type UserLogStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLogStreamRequest) Reset() {
	*x = UserLogStreamRequest{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLogStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLogStreamRequest) ProtoMessage() {}

func (x *UserLogStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLogStreamRequest.ProtoReflect.Descriptor instead.
func (*UserLogStreamRequest) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{20}
}

type ResetUserLoggingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enable        bool                   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	AppId         bool                   `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	SessionEnd    bool                   `protobuf:"varint,3,opt,name=session_end,json=sessionEnd,proto3" json:"session_end,omitempty"`
	RealtimeUsage bool                   `protobuf:"varint,4,opt,name=realtime_usage,json=realtimeUsage,proto3" json:"realtime_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetUserLoggingRequest) Reset() {
	*x = ResetUserLoggingRequest{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetUserLoggingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetUserLoggingRequest) ProtoMessage() {}

func (x *ResetUserLoggingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetUserLoggingRequest.ProtoReflect.Descriptor instead.
func (*ResetUserLoggingRequest) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{21}
}

func (x *ResetUserLoggingRequest) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *ResetUserLoggingRequest) GetAppId() bool {
	if x != nil {
		return x.AppId
	}
	return false
}

func (x *ResetUserLoggingRequest) GetSessionEnd() bool {
	if x != nil {
		return x.SessionEnd
	}
	return false
}

func (x *ResetUserLoggingRequest) GetRealtimeUsage() bool {
	if x != nil {
		return x.RealtimeUsage
	}
	return false
}

type ResetUserLoggingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetUserLoggingResponse) Reset() {
	*x = ResetUserLoggingResponse{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetUserLoggingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetUserLoggingResponse) ProtoMessage() {}

func (x *ResetUserLoggingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetUserLoggingResponse.ProtoReflect.Descriptor instead.
func (*ResetUserLoggingResponse) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{22}
}

// outbound
type ChangeOutboundRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// handlers to be added
	Handlers []*outbound.HandlerConfig `protobuf:"bytes,1,rep,name=handlers,proto3" json:"handlers,omitempty"`
	// handlers to be removed
	Tags []string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	// delete all proxy outbound handlers
	DeleteAll     bool `protobuf:"varint,3,opt,name=delete_all,json=deleteAll,proto3" json:"delete_all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeOutboundRequest) Reset() {
	*x = ChangeOutboundRequest{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeOutboundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeOutboundRequest) ProtoMessage() {}

func (x *ChangeOutboundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeOutboundRequest.ProtoReflect.Descriptor instead.
func (*ChangeOutboundRequest) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{23}
}

func (x *ChangeOutboundRequest) GetHandlers() []*outbound.HandlerConfig {
	if x != nil {
		return x.Handlers
	}
	return nil
}

func (x *ChangeOutboundRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ChangeOutboundRequest) GetDeleteAll() bool {
	if x != nil {
		return x.DeleteAll
	}
	return false
}

type ChangeOutboundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeOutboundResponse) Reset() {
	*x = ChangeOutboundResponse{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeOutboundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeOutboundResponse) ProtoMessage() {}

func (x *ChangeOutboundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeOutboundResponse.ProtoReflect.Descriptor instead.
func (*ChangeOutboundResponse) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{24}
}

type CurrentOutboundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentOutboundRequest) Reset() {
	*x = CurrentOutboundRequest{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentOutboundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentOutboundRequest) ProtoMessage() {}

func (x *CurrentOutboundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentOutboundRequest.ProtoReflect.Descriptor instead.
func (*CurrentOutboundRequest) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{25}
}

type CurrentOutboundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutboundTags  []string               `protobuf:"bytes,1,rep,name=outbound_tags,json=outboundTags,proto3" json:"outbound_tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentOutboundResponse) Reset() {
	*x = CurrentOutboundResponse{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentOutboundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentOutboundResponse) ProtoMessage() {}

func (x *CurrentOutboundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentOutboundResponse.ProtoReflect.Descriptor instead.
func (*CurrentOutboundResponse) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{26}
}

func (x *CurrentOutboundResponse) GetOutboundTags() []string {
	if x != nil {
		return x.OutboundTags
	}
	return nil
}

// routing
type ChangeRoutingModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouterConfig  *router.RouterConfig   `protobuf:"bytes,1,opt,name=router_config,json=routerConfig,proto3" json:"router_config,omitempty"`
	GeoConfig     *geo.GeoConfig         `protobuf:"bytes,2,opt,name=geo_config,json=geoConfig,proto3" json:"geo_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeRoutingModeRequest) Reset() {
	*x = ChangeRoutingModeRequest{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeRoutingModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeRoutingModeRequest) ProtoMessage() {}

func (x *ChangeRoutingModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeRoutingModeRequest.ProtoReflect.Descriptor instead.
func (*ChangeRoutingModeRequest) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{27}
}

func (x *ChangeRoutingModeRequest) GetRouterConfig() *router.RouterConfig {
	if x != nil {
		return x.RouterConfig
	}
	return nil
}

func (x *ChangeRoutingModeRequest) GetGeoConfig() *geo.GeoConfig {
	if x != nil {
		return x.GeoConfig
	}
	return nil
}

type ChangeRoutingModeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeRoutingModeResponse) Reset() {
	*x = ChangeRoutingModeResponse{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeRoutingModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeRoutingModeResponse) ProtoMessage() {}

func (x *ChangeRoutingModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeRoutingModeResponse.ProtoReflect.Descriptor instead.
func (*ChangeRoutingModeResponse) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{28}
}

type ChangeSelectorRequest struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	SelectorsToAdd   []*router.SelectorConfig `protobuf:"bytes,1,rep,name=selectors_to_add,json=selectorsToAdd,proto3" json:"selectors_to_add,omitempty"`
	SelectorToRemove string                   `protobuf:"bytes,2,opt,name=selector_to_remove,json=selectorToRemove,proto3" json:"selector_to_remove,omitempty"`
	DeleteAll        bool                     `protobuf:"varint,3,opt,name=delete_all,json=deleteAll,proto3" json:"delete_all,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChangeSelectorRequest) Reset() {
	*x = ChangeSelectorRequest{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeSelectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeSelectorRequest) ProtoMessage() {}

func (x *ChangeSelectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeSelectorRequest.ProtoReflect.Descriptor instead.
func (*ChangeSelectorRequest) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{29}
}

func (x *ChangeSelectorRequest) GetSelectorsToAdd() []*router.SelectorConfig {
	if x != nil {
		return x.SelectorsToAdd
	}
	return nil
}

func (x *ChangeSelectorRequest) GetSelectorToRemove() string {
	if x != nil {
		return x.SelectorToRemove
	}
	return ""
}

func (x *ChangeSelectorRequest) GetDeleteAll() bool {
	if x != nil {
		return x.DeleteAll
	}
	return false
}

type UpdateSelectorBalancerRequest struct {
	state           protoimpl.MessageState                `protogen:"open.v1"`
	Tag             string                                `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	BalanceStrategy router.SelectorConfig_BalanceStrategy `protobuf:"varint,2,opt,name=balance_strategy,json=balanceStrategy,proto3,enum=vx.router.SelectorConfig_BalanceStrategy" json:"balance_strategy,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateSelectorBalancerRequest) Reset() {
	*x = UpdateSelectorBalancerRequest{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSelectorBalancerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSelectorBalancerRequest) ProtoMessage() {}

func (x *UpdateSelectorBalancerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSelectorBalancerRequest.ProtoReflect.Descriptor instead.
func (*UpdateSelectorBalancerRequest) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{30}
}

func (x *UpdateSelectorBalancerRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *UpdateSelectorBalancerRequest) GetBalanceStrategy() router.SelectorConfig_BalanceStrategy {
	if x != nil {
		return x.BalanceStrategy
	}
	return router.SelectorConfig_BalanceStrategy(0)
}

type UpdateSelectorFilterRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Tag           string                        `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Filter        *router.SelectorConfig_Filter `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	SelectFromOm  bool                          `protobuf:"varint,3,opt,name=select_from_om,json=selectFromOm,proto3" json:"select_from_om,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSelectorFilterRequest) Reset() {
	*x = UpdateSelectorFilterRequest{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSelectorFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSelectorFilterRequest) ProtoMessage() {}

func (x *UpdateSelectorFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSelectorFilterRequest.ProtoReflect.Descriptor instead.
func (*UpdateSelectorFilterRequest) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{31}
}

func (x *UpdateSelectorFilterRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *UpdateSelectorFilterRequest) GetFilter() *router.SelectorConfig_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *UpdateSelectorFilterRequest) GetSelectFromOm() bool {
	if x != nil {
		return x.SelectFromOm
	}
	return false
}

type ChangeSelectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeSelectorResponse) Reset() {
	*x = ChangeSelectorResponse{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeSelectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeSelectorResponse) ProtoMessage() {}

func (x *ChangeSelectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeSelectorResponse.ProtoReflect.Descriptor instead.
func (*ChangeSelectorResponse) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{32}
}

type HandlerChangeNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandlerChangeNotify) Reset() {
	*x = HandlerChangeNotify{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlerChangeNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlerChangeNotify) ProtoMessage() {}

func (x *HandlerChangeNotify) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlerChangeNotify.ProtoReflect.Descriptor instead.
func (*HandlerChangeNotify) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{33}
}

type HandlerChangeNotifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandlerChangeNotifyResponse) Reset() {
	*x = HandlerChangeNotifyResponse{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlerChangeNotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlerChangeNotifyResponse) ProtoMessage() {}

func (x *HandlerChangeNotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlerChangeNotifyResponse.ProtoReflect.Descriptor instead.
func (*HandlerChangeNotifyResponse) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{34}
}

// fake dns
type SwitchFakeDnsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enable        bool                   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchFakeDnsRequest) Reset() {
	*x = SwitchFakeDnsRequest{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchFakeDnsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchFakeDnsRequest) ProtoMessage() {}

func (x *SwitchFakeDnsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchFakeDnsRequest.ProtoReflect.Descriptor instead.
func (*SwitchFakeDnsRequest) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{35}
}

func (x *SwitchFakeDnsRequest) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

type SwitchFakeDnsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchFakeDnsResponse) Reset() {
	*x = SwitchFakeDnsResponse{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchFakeDnsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchFakeDnsResponse) ProtoMessage() {}

func (x *SwitchFakeDnsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchFakeDnsResponse.ProtoReflect.Descriptor instead.
func (*SwitchFakeDnsResponse) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{36}
}

// geo
type UpdateGeoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Geo           *geo.GeoConfig         `protobuf:"bytes,1,opt,name=geo,proto3" json:"geo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGeoRequest) Reset() {
	*x = UpdateGeoRequest{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGeoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGeoRequest) ProtoMessage() {}

func (x *UpdateGeoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGeoRequest.ProtoReflect.Descriptor instead.
func (*UpdateGeoRequest) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{37}
}

func (x *UpdateGeoRequest) GetGeo() *geo.GeoConfig {
	if x != nil {
		return x.Geo
	}
	return nil
}

type UpdateGeoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGeoResponse) Reset() {
	*x = UpdateGeoResponse{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGeoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGeoResponse) ProtoMessage() {}

func (x *UpdateGeoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGeoResponse.ProtoReflect.Descriptor instead.
func (*UpdateGeoResponse) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{38}
}

type AddGeoDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DomainSetName string                 `protobuf:"bytes,1,opt,name=domain_set_name,json=domainSetName,proto3" json:"domain_set_name,omitempty"`
	Domain        *geo1.Domain           `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddGeoDomainRequest) Reset() {
	*x = AddGeoDomainRequest{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGeoDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGeoDomainRequest) ProtoMessage() {}

func (x *AddGeoDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGeoDomainRequest.ProtoReflect.Descriptor instead.
func (*AddGeoDomainRequest) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{39}
}

func (x *AddGeoDomainRequest) GetDomainSetName() string {
	if x != nil {
		return x.DomainSetName
	}
	return ""
}

func (x *AddGeoDomainRequest) GetDomain() *geo1.Domain {
	if x != nil {
		return x.Domain
	}
	return nil
}

type RemoveGeoDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DomainSetName string                 `protobuf:"bytes,1,opt,name=domain_set_name,json=domainSetName,proto3" json:"domain_set_name,omitempty"`
	Domain        *geo1.Domain           `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveGeoDomainRequest) Reset() {
	*x = RemoveGeoDomainRequest{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveGeoDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveGeoDomainRequest) ProtoMessage() {}

func (x *RemoveGeoDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveGeoDomainRequest.ProtoReflect.Descriptor instead.
func (*RemoveGeoDomainRequest) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{40}
}

func (x *RemoveGeoDomainRequest) GetDomainSetName() string {
	if x != nil {
		return x.DomainSetName
	}
	return ""
}

func (x *RemoveGeoDomainRequest) GetDomain() *geo1.Domain {
	if x != nil {
		return x.Domain
	}
	return nil
}

type ReplaceDomainSetRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Set           *geo.AtomicDomainSetConfig `protobuf:"bytes,1,opt,name=set,proto3" json:"set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceDomainSetRequest) Reset() {
	*x = ReplaceDomainSetRequest{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceDomainSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceDomainSetRequest) ProtoMessage() {}

func (x *ReplaceDomainSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceDomainSetRequest.ProtoReflect.Descriptor instead.
func (*ReplaceDomainSetRequest) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{41}
}

func (x *ReplaceDomainSetRequest) GetSet() *geo.AtomicDomainSetConfig {
	if x != nil {
		return x.Set
	}
	return nil
}

type ReplaceIPSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Set           *geo.AtomicIPSetConfig `protobuf:"bytes,1,opt,name=set,proto3" json:"set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceIPSetRequest) Reset() {
	*x = ReplaceIPSetRequest{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceIPSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceIPSetRequest) ProtoMessage() {}

func (x *ReplaceIPSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceIPSetRequest.ProtoReflect.Descriptor instead.
func (*ReplaceIPSetRequest) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{42}
}

func (x *ReplaceIPSetRequest) GetSet() *geo.AtomicIPSetConfig {
	if x != nil {
		return x.Set
	}
	return nil
}

// app id
type UpdateRouterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouterConfig  *router.RouterConfig   `protobuf:"bytes,1,opt,name=router_config,json=routerConfig,proto3" json:"router_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRouterRequest) Reset() {
	*x = UpdateRouterRequest{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRouterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRouterRequest) ProtoMessage() {}

func (x *UpdateRouterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRouterRequest.ProtoReflect.Descriptor instead.
func (*UpdateRouterRequest) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{43}
}

func (x *UpdateRouterRequest) GetRouterConfig() *router.RouterConfig {
	if x != nil {
		return x.RouterConfig
	}
	return nil
}

type UpdateRouterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRouterResponse) Reset() {
	*x = UpdateRouterResponse{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRouterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRouterResponse) ProtoMessage() {}

func (x *UpdateRouterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRouterResponse.ProtoReflect.Descriptor instead.
func (*UpdateRouterResponse) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{44}
}

// subscription
type SetSubscriptionIntervalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// minus means no auto update
	// minutes
	Interval      int32 `protobuf:"varint,1,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSubscriptionIntervalRequest) Reset() {
	*x = SetSubscriptionIntervalRequest{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSubscriptionIntervalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSubscriptionIntervalRequest) ProtoMessage() {}

func (x *SetSubscriptionIntervalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSubscriptionIntervalRequest.ProtoReflect.Descriptor instead.
func (*SetSubscriptionIntervalRequest) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{45}
}

func (x *SetSubscriptionIntervalRequest) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

type SetSubscriptionIntervalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSubscriptionIntervalResponse) Reset() {
	*x = SetSubscriptionIntervalResponse{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSubscriptionIntervalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSubscriptionIntervalResponse) ProtoMessage() {}

func (x *SetSubscriptionIntervalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSubscriptionIntervalResponse.ProtoReflect.Descriptor instead.
func (*SetSubscriptionIntervalResponse) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{46}
}

type SetAutoSubscriptionUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enable        bool                   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAutoSubscriptionUpdateRequest) Reset() {
	*x = SetAutoSubscriptionUpdateRequest{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAutoSubscriptionUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAutoSubscriptionUpdateRequest) ProtoMessage() {}

func (x *SetAutoSubscriptionUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAutoSubscriptionUpdateRequest.ProtoReflect.Descriptor instead.
func (*SetAutoSubscriptionUpdateRequest) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{47}
}

func (x *SetAutoSubscriptionUpdateRequest) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

type SetProxyShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enable        bool                   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	ListenAddr    string                 `protobuf:"bytes,2,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`
	ListenPort    uint32                 `protobuf:"varint,3,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetProxyShareRequest) Reset() {
	*x = SetProxyShareRequest{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[48]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetProxyShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProxyShareRequest) ProtoMessage() {}

func (x *SetProxyShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[48]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProxyShareRequest.ProtoReflect.Descriptor instead.
func (*SetProxyShareRequest) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{48}
}

func (x *SetProxyShareRequest) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *SetProxyShareRequest) GetListenAddr() string {
	if x != nil {
		return x.ListenAddr
	}
	return ""
}

func (x *SetProxyShareRequest) GetListenPort() uint32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

type SetProxyShareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetProxyShareResponse) Reset() {
	*x = SetProxyShareResponse{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[49]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetProxyShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProxyShareResponse) ProtoMessage() {}

func (x *SetProxyShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[49]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProxyShareResponse.ProtoReflect.Descriptor instead.
func (*SetProxyShareResponse) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{49}
}

type SelectedHandlersResponse_Strings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strings       []string               `protobuf:"bytes,1,rep,name=strings,proto3" json:"strings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectedHandlersResponse_Strings) Reset() {
	*x = SelectedHandlersResponse_Strings{}
	mi := &file_app_grpcservice_grpc_proto_msgTypes[50]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectedHandlersResponse_Strings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectedHandlersResponse_Strings) ProtoMessage() {}

func (x *SelectedHandlersResponse_Strings) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpcservice_grpc_proto_msgTypes[50]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectedHandlersResponse_Strings.ProtoReflect.Descriptor instead.
func (*SelectedHandlersResponse_Strings) Descriptor() ([]byte, []int) {
	return file_app_grpcservice_grpc_proto_rawDescGZIP(), []int{19, 0}
}

func (x *SelectedHandlersResponse_Strings) GetStrings() []string {
	if x != nil {
		return x.Strings
	}
	return nil
}

var File_app_grpcservice_grpc_proto protoreflect.FileDescriptor

const file_app_grpcservice_grpc_proto_rawDesc = "" +
	"\n" +
	"\x1aapp/grpcservice/grpc.proto\x12\x0evx.grpcservice\x1a\x1bapp/userlogger/config.proto\x1a\x17vx/common/geo/geo.proto\x1a\x10vx/geo/geo.proto\x1a\x18vx/inbound/inbound.proto\x1a\x1avx/outbound/outbound.proto\x1a\x16vx/router/router.proto\"8\n" +
	"\x0eRttTestRequest\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"%\n" +
	"\x0fRttTestResponse\x12\x12\n" +
	"\x04ping\x18\x01 \x01(\rR\x04ping\"\t\n" +
	"\aReceipt\"\x14\n" +
	"\x12CommunicateRequest\"\xd9\x02\n" +
	"\x12CommunicateMessage\x12C\n" +
	"\rhandler_error\x18\x01 \x01(\v2\x1c.vx.grpcservice.HandlerErrorH\x00R\fhandlerError\x12V\n" +
	"\x13subscription_update\x18\x02 \x01(\v2#.vx.grpcservice.SubscriptionUpdatedH\x00R\x12subscriptionUpdate\x12P\n" +
	"\x12handler_being_used\x18\x03 \x01(\v2 .vx.grpcservice.HandlerBeingUsedH\x00R\x10handlerBeingUsed\x12I\n" +
	"\x0fhandler_updated\x18\x04 \x01(\v2\x1e.vx.grpcservice.HandlerUpdatedH\x00R\x0ehandlerUpdatedB\t\n" +
	"\amessage\"6\n" +
	"\fHandlerError\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"B\n" +
	"\x10HandlerBeingUsed\x12\x1a\n" +
	"\bselector\x18\x01 \x01(\tR\bselector\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\" \n" +
	"\x0eHandlerUpdated\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x15\n" +
	"\x13SubscriptionUpdated\"Z\n" +
	"\x11AddInboundRequest\x12E\n" +
	"\x0ehandler_config\x18\x01 \x01(\v2\x1e.vx.inbound.ProxyInboundConfigR\rhandlerConfig\"\x14\n" +
	"\x12AddInboundResponse\"(\n" +
	"\x14RemoveInboundRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\"\x17\n" +
	"\x15RemoveInboundResponse\"\x87\x01\n" +
	"\rOutboundStats\x12\x0e\n" +
	"\x02up\x18\x01 \x01(\x04R\x02up\x12\x12\n" +
	"\x04down\x18\x02 \x01(\x04R\x04down\x12\x12\n" +
	"\x04rate\x18\x03 \x01(\x04R\x04rate\x12\x12\n" +
	"\x04ping\x18\x04 \x01(\x04R\x04ping\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\tR\x02id\x12\x1a\n" +
	"\binterval\x18\x06 \x01(\x02R\binterval\"-\n" +
	"\x0fGetStatsRequest\x12\x1a\n" +
	"\binterval\x18\x01 \x01(\rR\binterval\"~\n" +
	"\rStatsResponse\x123\n" +
	"\x05stats\x18\x01 \x03(\v2\x1d.vx.grpcservice.OutboundStatsR\x05stats\x12 \n" +
	"\vconnections\x18\x02 \x01(\x05R\vconnections\x12\x16\n" +
	"\x06memory\x18\x03 \x01(\x04R\x06memory\"H\n" +
	"\x1eSetOutboundHandlerSpeedRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x14\n" +
	"\x05speed\x18\x02 \x01(\x05R\x05speed\"!\n" +
	"\x1fSetOutboundHandlerSpeedResponse\"\x19\n" +
	"\x17SelectedHandlersRequest\"\xa3\x02\n" +
	"\x18SelectedHandlersResponse\x12k\n" +
	"\x11selected_handlers\x18\x01 \x03(\v2>.vx.grpcservice.SelectedHandlersResponse.SelectedHandlersEntryR\x10selectedHandlers\x1a#\n" +
	"\aStrings\x12\x18\n" +
	"\astrings\x18\x01 \x03(\tR\astrings\x1au\n" +
	"\x15SelectedHandlersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12F\n" +
	"\x05value\x18\x02 \x01(\v20.vx.grpcservice.SelectedHandlersResponse.StringsR\x05value:\x028\x01\"\x16\n" +
	"\x14UserLogStreamRequest\"\x90\x01\n" +
	"\x17ResetUserLoggingRequest\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\bR\x05appId\x12\x1f\n" +
	"\vsession_end\x18\x03 \x01(\bR\n" +
	"sessionEnd\x12%\n" +
	"\x0erealtime_usage\x18\x04 \x01(\bR\rrealtimeUsage\"\x1a\n" +
	"\x18ResetUserLoggingResponse\"\x82\x01\n" +
	"\x15ChangeOutboundRequest\x126\n" +
	"\bhandlers\x18\x01 \x03(\v2\x1a.vx.outbound.HandlerConfigR\bhandlers\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"delete_all\x18\x03 \x01(\bR\tdeleteAll\"\x18\n" +
	"\x16ChangeOutboundResponse\"\x18\n" +
	"\x16CurrentOutboundRequest\">\n" +
	"\x17CurrentOutboundResponse\x12#\n" +
	"\routbound_tags\x18\x01 \x03(\tR\foutboundTags\"\x8a\x01\n" +
	"\x18ChangeRoutingModeRequest\x12<\n" +
	"\rrouter_config\x18\x01 \x01(\v2\x17.vx.router.RouterConfigR\frouterConfig\x120\n" +
	"\n" +
	"geo_config\x18\x02 \x01(\v2\x11.vx.geo.GeoConfigR\tgeoConfig\"\x1b\n" +
	"\x19ChangeRoutingModeResponse\"\xa9\x01\n" +
	"\x15ChangeSelectorRequest\x12C\n" +
	"\x10selectors_to_add\x18\x01 \x03(\v2\x19.vx.router.SelectorConfigR\x0eselectorsToAdd\x12,\n" +
	"\x12selector_to_remove\x18\x02 \x01(\tR\x10selectorToRemove\x12\x1d\n" +
	"\n" +
	"delete_all\x18\x03 \x01(\bR\tdeleteAll\"\x87\x01\n" +
	"\x1dUpdateSelectorBalancerRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12T\n" +
	"\x10balance_strategy\x18\x02 \x01(\x0e2).vx.router.SelectorConfig.BalanceStrategyR\x0fbalanceStrategy\"\x8f\x01\n" +
	"\x1bUpdateSelectorFilterRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x128\n" +
	"\x06filter\x18\x02 \x01(\v2 .vx.router.SelectorConfig.FilterR\x06filter\x12$\n" +
	"\x0eselect_from_om\x18\x03 \x01(\bR\fselectFromOm\"\x18\n" +
	"\x16ChangeSelectorResponse\"\x15\n" +
	"\x13HandlerChangeNotify\"\x1d\n" +
	"\x1bHandlerChangeNotifyResponse\".\n" +
	"\x14SwitchFakeDnsRequest\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\"\x17\n" +
	"\x15SwitchFakeDnsResponse\"7\n" +
	"\x10UpdateGeoRequest\x12#\n" +
	"\x03geo\x18\x01 \x01(\v2\x11.vx.geo.GeoConfigR\x03geo\"\x13\n" +
	"\x11UpdateGeoResponse\"l\n" +
	"\x13AddGeoDomainRequest\x12&\n" +
	"\x0fdomain_set_name\x18\x01 \x01(\tR\rdomainSetName\x12-\n" +
	"\x06domain\x18\x02 \x01(\v2\x15.vx.common.geo.DomainR\x06domain\"o\n" +
	"\x16RemoveGeoDomainRequest\x12&\n" +
	"\x0fdomain_set_name\x18\x01 \x01(\tR\rdomainSetName\x12-\n" +
	"\x06domain\x18\x02 \x01(\v2\x15.vx.common.geo.DomainR\x06domain\"J\n" +
	"\x17ReplaceDomainSetRequest\x12/\n" +
	"\x03set\x18\x01 \x01(\v2\x1d.vx.geo.AtomicDomainSetConfigR\x03set\"B\n" +
	"\x13ReplaceIPSetRequest\x12+\n" +
	"\x03set\x18\x01 \x01(\v2\x19.vx.geo.AtomicIPSetConfigR\x03set\"S\n" +
	"\x13UpdateRouterRequest\x12<\n" +
	"\rrouter_config\x18\x01 \x01(\v2\x17.vx.router.RouterConfigR\frouterConfig\"\x16\n" +
	"\x14UpdateRouterResponse\"<\n" +
	"\x1eSetSubscriptionIntervalRequest\x12\x1a\n" +
	"\binterval\x18\x01 \x01(\x05R\binterval\"!\n" +
	"\x1fSetSubscriptionIntervalResponse\":\n" +
	" SetAutoSubscriptionUpdateRequest\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\"p\n" +
	"\x14SetProxyShareRequest\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\x12\x1f\n" +
	"\vlisten_addr\x18\x02 \x01(\tR\n" +
	"listenAddr\x12\x1f\n" +
	"\vlisten_port\x18\x03 \x01(\rR\n" +
	"listenPort\"\x17\n" +
	"\x15SetProxyShareResponse2\xcd\x12\n" +
	"\vGrpcService\x12W\n" +
	"\vCommunicate\x12\".vx.grpcservice.CommunicateRequest\x1a\".vx.grpcservice.CommunicateMessage0\x01\x12S\n" +
	"\n" +
	"AddInbound\x12!.vx.grpcservice.AddInboundRequest\x1a\".vx.grpcservice.AddInboundResponse\x12\\\n" +
	"\rRemoveInbound\x12$.vx.grpcservice.RemoveInboundRequest\x1a%.vx.grpcservice.RemoveInboundResponse\x12T\n" +
	"\x0eGetStatsStream\x12\x1f.vx.grpcservice.GetStatsRequest\x1a\x1d.vx.grpcservice.StatsResponse\"\x000\x01\x12z\n" +
	"\x17SetOutboundHandlerSpeed\x12..vx.grpcservice.SetOutboundHandlerSpeedRequest\x1a/.vx.grpcservice.SetOutboundHandlerSpeedResponse\x12V\n" +
	"\rUserLogStream\x12$.vx.grpcservice.UserLogStreamRequest\x1a\x1d.vx.userlogger.UserLogMessage0\x01\x12e\n" +
	"\x10ResetUserLogging\x12'.vx.grpcservice.ResetUserLoggingRequest\x1a(.vx.grpcservice.ResetUserLoggingResponse\x12_\n" +
	"\x0eChangeOutbound\x12%.vx.grpcservice.ChangeOutboundRequest\x1a&.vx.grpcservice.ChangeOutboundResponse\x12b\n" +
	"\x0fCurrentOutbound\x12&.vx.grpcservice.CurrentOutboundRequest\x1a'.vx.grpcservice.CurrentOutboundResponse\x12e\n" +
	"\x10SelectedHandlers\x12'.vx.grpcservice.SelectedHandlersRequest\x1a(.vx.grpcservice.SelectedHandlersResponse\x12h\n" +
	"\x11ChangeRoutingMode\x12(.vx.grpcservice.ChangeRoutingModeRequest\x1a).vx.grpcservice.ChangeRoutingModeResponse\x12_\n" +
	"\x0eChangeSelector\x12%.vx.grpcservice.ChangeSelectorRequest\x1a&.vx.grpcservice.ChangeSelectorResponse\x12`\n" +
	"\x16UpdateSelectorBalancer\x12-.vx.grpcservice.UpdateSelectorBalancerRequest\x1a\x17.vx.grpcservice.Receipt\x12\\\n" +
	"\x14UpdateSelectorFilter\x12+.vx.grpcservice.UpdateSelectorFilterRequest\x1a\x17.vx.grpcservice.Receipt\x12g\n" +
	"\x13NotifyHandlerChange\x12#.vx.grpcservice.HandlerChangeNotify\x1a+.vx.grpcservice.HandlerChangeNotifyResponse\x12\\\n" +
	"\rSwitchFakeDns\x12$.vx.grpcservice.SwitchFakeDnsRequest\x1a%.vx.grpcservice.SwitchFakeDnsResponse\x12P\n" +
	"\tUpdateGeo\x12 .vx.grpcservice.UpdateGeoRequest\x1a!.vx.grpcservice.UpdateGeoResponse\x12L\n" +
	"\fAddGeoDomain\x12#.vx.grpcservice.AddGeoDomainRequest\x1a\x17.vx.grpcservice.Receipt\x12R\n" +
	"\x0fRemoveGeoDomain\x12&.vx.grpcservice.RemoveGeoDomainRequest\x1a\x17.vx.grpcservice.Receipt\x12U\n" +
	"\x11ReplaceGeoDomains\x12'.vx.grpcservice.ReplaceDomainSetRequest\x1a\x17.vx.grpcservice.Receipt\x12M\n" +
	"\rReplaceGeoIPs\x12#.vx.grpcservice.ReplaceIPSetRequest\x1a\x17.vx.grpcservice.Receipt\x12Y\n" +
	"\fUpdateRouter\x12#.vx.grpcservice.UpdateRouterRequest\x1a$.vx.grpcservice.UpdateRouterResponse\x12z\n" +
	"\x17SetSubscriptionInterval\x12..vx.grpcservice.SetSubscriptionIntervalRequest\x1a/.vx.grpcservice.SetSubscriptionIntervalResponse\x12f\n" +
	"\x19SetAutoSubscriptionUpdate\x120.vx.grpcservice.SetAutoSubscriptionUpdateRequest\x1a\x17.vx.grpcservice.Receipt\x12J\n" +
	"\aRttTest\x12\x1e.vx.grpcservice.RttTestRequest\x1a\x1f.vx.grpcservice.RttTestResponseB\xa6\x01\n" +
	"\x12com.vx.grpcserviceB\tGrpcProtoP\x01Z,github.com/5vnetwork/vx-core/app/grpcservice\xa2\x02\x03VGX\xaa\x02\x0eVx.Grpcservice\xca\x02\x0eVx\\Grpcservice\xe2\x02\x1aVx\\Grpcservice\\GPBMetadata\xea\x02\x0fVx::Grpcserviceb\x06proto3"

var (
	file_app_grpcservice_grpc_proto_rawDescOnce sync.Once
	file_app_grpcservice_grpc_proto_rawDescData []byte
)

func file_app_grpcservice_grpc_proto_rawDescGZIP() []byte {
	file_app_grpcservice_grpc_proto_rawDescOnce.Do(func() {
		file_app_grpcservice_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_grpcservice_grpc_proto_rawDesc), len(file_app_grpcservice_grpc_proto_rawDesc)))
	})
	return file_app_grpcservice_grpc_proto_rawDescData
}

var file_app_grpcservice_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 52)
var file_app_grpcservice_grpc_proto_goTypes = []any{
	(*RttTestRequest)(nil),                     // 0: vx.grpcservice.RttTestRequest
	(*RttTestResponse)(nil),                    // 1: vx.grpcservice.RttTestResponse
	(*Receipt)(nil),                            // 2: vx.grpcservice.Receipt
	(*CommunicateRequest)(nil),                 // 3: vx.grpcservice.CommunicateRequest
	(*CommunicateMessage)(nil),                 // 4: vx.grpcservice.CommunicateMessage
	(*HandlerError)(nil),                       // 5: vx.grpcservice.HandlerError
	(*HandlerBeingUsed)(nil),                   // 6: vx.grpcservice.HandlerBeingUsed
	(*HandlerUpdated)(nil),                     // 7: vx.grpcservice.HandlerUpdated
	(*SubscriptionUpdated)(nil),                // 8: vx.grpcservice.SubscriptionUpdated
	(*AddInboundRequest)(nil),                  // 9: vx.grpcservice.AddInboundRequest
	(*AddInboundResponse)(nil),                 // 10: vx.grpcservice.AddInboundResponse
	(*RemoveInboundRequest)(nil),               // 11: vx.grpcservice.RemoveInboundRequest
	(*RemoveInboundResponse)(nil),              // 12: vx.grpcservice.RemoveInboundResponse
	(*OutboundStats)(nil),                      // 13: vx.grpcservice.OutboundStats
	(*GetStatsRequest)(nil),                    // 14: vx.grpcservice.GetStatsRequest
	(*StatsResponse)(nil),                      // 15: vx.grpcservice.StatsResponse
	(*SetOutboundHandlerSpeedRequest)(nil),     // 16: vx.grpcservice.SetOutboundHandlerSpeedRequest
	(*SetOutboundHandlerSpeedResponse)(nil),    // 17: vx.grpcservice.SetOutboundHandlerSpeedResponse
	(*SelectedHandlersRequest)(nil),            // 18: vx.grpcservice.SelectedHandlersRequest
	(*SelectedHandlersResponse)(nil),           // 19: vx.grpcservice.SelectedHandlersResponse
	(*UserLogStreamRequest)(nil),               // 20: vx.grpcservice.UserLogStreamRequest
	(*ResetUserLoggingRequest)(nil),            // 21: vx.grpcservice.ResetUserLoggingRequest
	(*ResetUserLoggingResponse)(nil),           // 22: vx.grpcservice.ResetUserLoggingResponse
	(*ChangeOutboundRequest)(nil),              // 23: vx.grpcservice.ChangeOutboundRequest
	(*ChangeOutboundResponse)(nil),             // 24: vx.grpcservice.ChangeOutboundResponse
	(*CurrentOutboundRequest)(nil),             // 25: vx.grpcservice.CurrentOutboundRequest
	(*CurrentOutboundResponse)(nil),            // 26: vx.grpcservice.CurrentOutboundResponse
	(*ChangeRoutingModeRequest)(nil),           // 27: vx.grpcservice.ChangeRoutingModeRequest
	(*ChangeRoutingModeResponse)(nil),          // 28: vx.grpcservice.ChangeRoutingModeResponse
	(*ChangeSelectorRequest)(nil),              // 29: vx.grpcservice.ChangeSelectorRequest
	(*UpdateSelectorBalancerRequest)(nil),      // 30: vx.grpcservice.UpdateSelectorBalancerRequest
	(*UpdateSelectorFilterRequest)(nil),        // 31: vx.grpcservice.UpdateSelectorFilterRequest
	(*ChangeSelectorResponse)(nil),             // 32: vx.grpcservice.ChangeSelectorResponse
	(*HandlerChangeNotify)(nil),                // 33: vx.grpcservice.HandlerChangeNotify
	(*HandlerChangeNotifyResponse)(nil),        // 34: vx.grpcservice.HandlerChangeNotifyResponse
	(*SwitchFakeDnsRequest)(nil),               // 35: vx.grpcservice.SwitchFakeDnsRequest
	(*SwitchFakeDnsResponse)(nil),              // 36: vx.grpcservice.SwitchFakeDnsResponse
	(*UpdateGeoRequest)(nil),                   // 37: vx.grpcservice.UpdateGeoRequest
	(*UpdateGeoResponse)(nil),                  // 38: vx.grpcservice.UpdateGeoResponse
	(*AddGeoDomainRequest)(nil),                // 39: vx.grpcservice.AddGeoDomainRequest
	(*RemoveGeoDomainRequest)(nil),             // 40: vx.grpcservice.RemoveGeoDomainRequest
	(*ReplaceDomainSetRequest)(nil),            // 41: vx.grpcservice.ReplaceDomainSetRequest
	(*ReplaceIPSetRequest)(nil),                // 42: vx.grpcservice.ReplaceIPSetRequest
	(*UpdateRouterRequest)(nil),                // 43: vx.grpcservice.UpdateRouterRequest
	(*UpdateRouterResponse)(nil),               // 44: vx.grpcservice.UpdateRouterResponse
	(*SetSubscriptionIntervalRequest)(nil),     // 45: vx.grpcservice.SetSubscriptionIntervalRequest
	(*SetSubscriptionIntervalResponse)(nil),    // 46: vx.grpcservice.SetSubscriptionIntervalResponse
	(*SetAutoSubscriptionUpdateRequest)(nil),   // 47: vx.grpcservice.SetAutoSubscriptionUpdateRequest
	(*SetProxyShareRequest)(nil),               // 48: vx.grpcservice.SetProxyShareRequest
	(*SetProxyShareResponse)(nil),              // 49: vx.grpcservice.SetProxyShareResponse
	(*SelectedHandlersResponse_Strings)(nil),   // 50: vx.grpcservice.SelectedHandlersResponse.Strings
	nil,                                        // 51: vx.grpcservice.SelectedHandlersResponse.SelectedHandlersEntry
	(*inbound.ProxyInboundConfig)(nil),         // 52: vx.inbound.ProxyInboundConfig
	(*outbound.HandlerConfig)(nil),             // 53: vx.outbound.HandlerConfig
	(*router.RouterConfig)(nil),                // 54: vx.router.RouterConfig
	(*geo.GeoConfig)(nil),                      // 55: vx.geo.GeoConfig
	(*router.SelectorConfig)(nil),              // 56: vx.router.SelectorConfig
	(router.SelectorConfig_BalanceStrategy)(0), // 57: vx.router.SelectorConfig.BalanceStrategy
	(*router.SelectorConfig_Filter)(nil),       // 58: vx.router.SelectorConfig.Filter
	(*geo1.Domain)(nil),                        // 59: vx.common.geo.Domain
	(*geo.AtomicDomainSetConfig)(nil),          // 60: vx.geo.AtomicDomainSetConfig
	(*geo.AtomicIPSetConfig)(nil),              // 61: vx.geo.AtomicIPSetConfig
	(*userlogger.UserLogMessage)(nil),          // 62: vx.userlogger.UserLogMessage
}
var file_app_grpcservice_grpc_proto_depIdxs = []int32{
	5,  // 0: vx.grpcservice.CommunicateMessage.handler_error:type_name -> vx.grpcservice.HandlerError
	8,  // 1: vx.grpcservice.CommunicateMessage.subscription_update:type_name -> vx.grpcservice.SubscriptionUpdated
	6,  // 2: vx.grpcservice.CommunicateMessage.handler_being_used:type_name -> vx.grpcservice.HandlerBeingUsed
	7,  // 3: vx.grpcservice.CommunicateMessage.handler_updated:type_name -> vx.grpcservice.HandlerUpdated
	52, // 4: vx.grpcservice.AddInboundRequest.handler_config:type_name -> vx.inbound.ProxyInboundConfig
	13, // 5: vx.grpcservice.StatsResponse.stats:type_name -> vx.grpcservice.OutboundStats
	51, // 6: vx.grpcservice.SelectedHandlersResponse.selected_handlers:type_name -> vx.grpcservice.SelectedHandlersResponse.SelectedHandlersEntry
	53, // 7: vx.grpcservice.ChangeOutboundRequest.handlers:type_name -> vx.outbound.HandlerConfig
	54, // 8: vx.grpcservice.ChangeRoutingModeRequest.router_config:type_name -> vx.router.RouterConfig
	55, // 9: vx.grpcservice.ChangeRoutingModeRequest.geo_config:type_name -> vx.geo.GeoConfig
	56, // 10: vx.grpcservice.ChangeSelectorRequest.selectors_to_add:type_name -> vx.router.SelectorConfig
	57, // 11: vx.grpcservice.UpdateSelectorBalancerRequest.balance_strategy:type_name -> vx.router.SelectorConfig.BalanceStrategy
	58, // 12: vx.grpcservice.UpdateSelectorFilterRequest.filter:type_name -> vx.router.SelectorConfig.Filter
	55, // 13: vx.grpcservice.UpdateGeoRequest.geo:type_name -> vx.geo.GeoConfig
	59, // 14: vx.grpcservice.AddGeoDomainRequest.domain:type_name -> vx.common.geo.Domain
	59, // 15: vx.grpcservice.RemoveGeoDomainRequest.domain:type_name -> vx.common.geo.Domain
	60, // 16: vx.grpcservice.ReplaceDomainSetRequest.set:type_name -> vx.geo.AtomicDomainSetConfig
	61, // 17: vx.grpcservice.ReplaceIPSetRequest.set:type_name -> vx.geo.AtomicIPSetConfig
	54, // 18: vx.grpcservice.UpdateRouterRequest.router_config:type_name -> vx.router.RouterConfig
	50, // 19: vx.grpcservice.SelectedHandlersResponse.SelectedHandlersEntry.value:type_name -> vx.grpcservice.SelectedHandlersResponse.Strings
	3,  // 20: vx.grpcservice.GrpcService.Communicate:input_type -> vx.grpcservice.CommunicateRequest
	9,  // 21: vx.grpcservice.GrpcService.AddInbound:input_type -> vx.grpcservice.AddInboundRequest
	11, // 22: vx.grpcservice.GrpcService.RemoveInbound:input_type -> vx.grpcservice.RemoveInboundRequest
	14, // 23: vx.grpcservice.GrpcService.GetStatsStream:input_type -> vx.grpcservice.GetStatsRequest
	16, // 24: vx.grpcservice.GrpcService.SetOutboundHandlerSpeed:input_type -> vx.grpcservice.SetOutboundHandlerSpeedRequest
	20, // 25: vx.grpcservice.GrpcService.UserLogStream:input_type -> vx.grpcservice.UserLogStreamRequest
	21, // 26: vx.grpcservice.GrpcService.ResetUserLogging:input_type -> vx.grpcservice.ResetUserLoggingRequest
	23, // 27: vx.grpcservice.GrpcService.ChangeOutbound:input_type -> vx.grpcservice.ChangeOutboundRequest
	25, // 28: vx.grpcservice.GrpcService.CurrentOutbound:input_type -> vx.grpcservice.CurrentOutboundRequest
	18, // 29: vx.grpcservice.GrpcService.SelectedHandlers:input_type -> vx.grpcservice.SelectedHandlersRequest
	27, // 30: vx.grpcservice.GrpcService.ChangeRoutingMode:input_type -> vx.grpcservice.ChangeRoutingModeRequest
	29, // 31: vx.grpcservice.GrpcService.ChangeSelector:input_type -> vx.grpcservice.ChangeSelectorRequest
	30, // 32: vx.grpcservice.GrpcService.UpdateSelectorBalancer:input_type -> vx.grpcservice.UpdateSelectorBalancerRequest
	31, // 33: vx.grpcservice.GrpcService.UpdateSelectorFilter:input_type -> vx.grpcservice.UpdateSelectorFilterRequest
	33, // 34: vx.grpcservice.GrpcService.NotifyHandlerChange:input_type -> vx.grpcservice.HandlerChangeNotify
	35, // 35: vx.grpcservice.GrpcService.SwitchFakeDns:input_type -> vx.grpcservice.SwitchFakeDnsRequest
	37, // 36: vx.grpcservice.GrpcService.UpdateGeo:input_type -> vx.grpcservice.UpdateGeoRequest
	39, // 37: vx.grpcservice.GrpcService.AddGeoDomain:input_type -> vx.grpcservice.AddGeoDomainRequest
	40, // 38: vx.grpcservice.GrpcService.RemoveGeoDomain:input_type -> vx.grpcservice.RemoveGeoDomainRequest
	41, // 39: vx.grpcservice.GrpcService.ReplaceGeoDomains:input_type -> vx.grpcservice.ReplaceDomainSetRequest
	42, // 40: vx.grpcservice.GrpcService.ReplaceGeoIPs:input_type -> vx.grpcservice.ReplaceIPSetRequest
	43, // 41: vx.grpcservice.GrpcService.UpdateRouter:input_type -> vx.grpcservice.UpdateRouterRequest
	45, // 42: vx.grpcservice.GrpcService.SetSubscriptionInterval:input_type -> vx.grpcservice.SetSubscriptionIntervalRequest
	47, // 43: vx.grpcservice.GrpcService.SetAutoSubscriptionUpdate:input_type -> vx.grpcservice.SetAutoSubscriptionUpdateRequest
	0,  // 44: vx.grpcservice.GrpcService.RttTest:input_type -> vx.grpcservice.RttTestRequest
	4,  // 45: vx.grpcservice.GrpcService.Communicate:output_type -> vx.grpcservice.CommunicateMessage
	10, // 46: vx.grpcservice.GrpcService.AddInbound:output_type -> vx.grpcservice.AddInboundResponse
	12, // 47: vx.grpcservice.GrpcService.RemoveInbound:output_type -> vx.grpcservice.RemoveInboundResponse
	15, // 48: vx.grpcservice.GrpcService.GetStatsStream:output_type -> vx.grpcservice.StatsResponse
	17, // 49: vx.grpcservice.GrpcService.SetOutboundHandlerSpeed:output_type -> vx.grpcservice.SetOutboundHandlerSpeedResponse
	62, // 50: vx.grpcservice.GrpcService.UserLogStream:output_type -> vx.userlogger.UserLogMessage
	22, // 51: vx.grpcservice.GrpcService.ResetUserLogging:output_type -> vx.grpcservice.ResetUserLoggingResponse
	24, // 52: vx.grpcservice.GrpcService.ChangeOutbound:output_type -> vx.grpcservice.ChangeOutboundResponse
	26, // 53: vx.grpcservice.GrpcService.CurrentOutbound:output_type -> vx.grpcservice.CurrentOutboundResponse
	19, // 54: vx.grpcservice.GrpcService.SelectedHandlers:output_type -> vx.grpcservice.SelectedHandlersResponse
	28, // 55: vx.grpcservice.GrpcService.ChangeRoutingMode:output_type -> vx.grpcservice.ChangeRoutingModeResponse
	32, // 56: vx.grpcservice.GrpcService.ChangeSelector:output_type -> vx.grpcservice.ChangeSelectorResponse
	2,  // 57: vx.grpcservice.GrpcService.UpdateSelectorBalancer:output_type -> vx.grpcservice.Receipt
	2,  // 58: vx.grpcservice.GrpcService.UpdateSelectorFilter:output_type -> vx.grpcservice.Receipt
	34, // 59: vx.grpcservice.GrpcService.NotifyHandlerChange:output_type -> vx.grpcservice.HandlerChangeNotifyResponse
	36, // 60: vx.grpcservice.GrpcService.SwitchFakeDns:output_type -> vx.grpcservice.SwitchFakeDnsResponse
	38, // 61: vx.grpcservice.GrpcService.UpdateGeo:output_type -> vx.grpcservice.UpdateGeoResponse
	2,  // 62: vx.grpcservice.GrpcService.AddGeoDomain:output_type -> vx.grpcservice.Receipt
	2,  // 63: vx.grpcservice.GrpcService.RemoveGeoDomain:output_type -> vx.grpcservice.Receipt
	2,  // 64: vx.grpcservice.GrpcService.ReplaceGeoDomains:output_type -> vx.grpcservice.Receipt
	2,  // 65: vx.grpcservice.GrpcService.ReplaceGeoIPs:output_type -> vx.grpcservice.Receipt
	44, // 66: vx.grpcservice.GrpcService.UpdateRouter:output_type -> vx.grpcservice.UpdateRouterResponse
	46, // 67: vx.grpcservice.GrpcService.SetSubscriptionInterval:output_type -> vx.grpcservice.SetSubscriptionIntervalResponse
	2,  // 68: vx.grpcservice.GrpcService.SetAutoSubscriptionUpdate:output_type -> vx.grpcservice.Receipt
	1,  // 69: vx.grpcservice.GrpcService.RttTest:output_type -> vx.grpcservice.RttTestResponse
	45, // [45:70] is the sub-list for method output_type
	20, // [20:45] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_app_grpcservice_grpc_proto_init() }
func file_app_grpcservice_grpc_proto_init() {
	if File_app_grpcservice_grpc_proto != nil {
		return
	}
	file_app_grpcservice_grpc_proto_msgTypes[4].OneofWrappers = []any{
		(*CommunicateMessage_HandlerError)(nil),
		(*CommunicateMessage_SubscriptionUpdate)(nil),
		(*CommunicateMessage_HandlerBeingUsed)(nil),
		(*CommunicateMessage_HandlerUpdated)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_grpcservice_grpc_proto_rawDesc), len(file_app_grpcservice_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   52,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_grpcservice_grpc_proto_goTypes,
		DependencyIndexes: file_app_grpcservice_grpc_proto_depIdxs,
		MessageInfos:      file_app_grpcservice_grpc_proto_msgTypes,
	}.Build()
	File_app_grpcservice_grpc_proto = out.File
	file_app_grpcservice_grpc_proto_goTypes = nil
	file_app_grpcservice_grpc_proto_depIdxs = nil
}
